Tiber upgrade
autonity/docs.autonity.org pull request #259
Opened 2024-11-19 15:38 UTC by cmjc

🚧 WIP 🚧 

Documentation PR to add:

- Inflation mechanism.
  - Concepts, Protocol assets, Newton: Summary overview of NTN total supply and inflation mechanism
  - Glossary: terms for participation rate, inflation rewards, inflation mechanism
-

2025-03-26 15:52 UTC, cmjc commented
@aiman @yazzaoui @vpiyush @Jason-Zhangxin-Chen @lorenzo-dev1 @tbssajal @ScottRMalley 

Marking the docs.autonity.org **Tiber Upgrade** PR Ready for Review 👍

2025-04-02 13:22 UTC, Jason-Zhangxin-Chen submitted a review, later dismissed
LGTM.

2025-04-02 13:22 UTC, Jason-Zhangxin-Chen commented on concepts/oracle-server/index.md
> +
ATN-NTN price is computed by prices of ATN-USDCx and NTN-USDCx price which are sourced from AMM marketplace.

2025-04-02 13:22 UTC, Jason-Zhangxin-Chen commented on concepts/oafd/index.md
> +#### Price report
In this section, it would be better to mention that the fee cost of the report is reinbursed by the Autonity L1 protocol. Any honest data report accepted by the protocol are reinbursed automatically.

2025-04-11 13:29 UTC, lorenzo-dev1 reviewed
Partial review, flushing out comments so that they can be started to work on

2025-04-11 13:29 UTC, lorenzo-dev1 commented on glossary/index.md
> +For transaction gossiping between nodes the Ethereum wire protocol is used for P2P propagation of block announcements and transactions. For consensus gossiping a separate consensus protocol runs alon
```suggestion
The Ethereum wire protocol is used for P2P propagation of blocks and transactions between nodes. For consensus gossiping a separate protocol runs alongside the ethwire protocol, allowing for the execution of Autonity’s BFT Tendermint Consensus algorithm. For detail see [Communication layer](/concepts/architecture/#communication-layer) in the *Architecture* Concept.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on glossary/index.md
> +See [delegated](/glossary/#delegated) and [self-bonded](/glossary/#self-bonded).
autobonding happens also for ntn rewards accrued by self bonded stake (not only the delegated one).

2025-04-11 13:29 UTC, lorenzo-dev1 commented on glossary/index.md
> +Inflation rewards are emitted in the form of newton inflation (i.e. newly minted newton supply) for bonded stake [participating](/glossary/#participation-rate) in securing the [Autonity network](/glo
```suggestion
Inflation rewards are emitted in the form of newton inflation (i.e. newly minted newton supply) for bonded stake [participating](/glossary/#participation-rate) in securing the [Autonity network](/glossary/#autonity-network). The quantity of newton emissions declines (in average) over time and asymptotically approaches zero.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on glossary/index.md
> +- The validator is found inactive while on probation by [Omission fault detection](/concepts/ofd/#jail-period-calculation).
```suggestion
- The validator is repeatedly found inactive while on probation by [Omission fault detection](/concepts/ofd/#jail-period-calculation), leading to a cumulative 100% slashing penalty.
```

Just to be more precise and not cause panic, as you cannot be jailbound if you are offline once while on probation

2025-04-11 13:29 UTC, lorenzo-dev1 commented on glossary/index.md
> +Newton is not redeemed to the stake [delegator](/glossary/#delegation) until the end of the [epoch](/glossary/#epoch) in which the unbonding period expires.
Might be worth to substitute redeemed with minted also here

2025-04-11 13:29 UTC, lorenzo-dev1 commented on glossary/index.md
not a big deal, but I would rather merge these 2 to reduce potential confusion, as it seems to me that their meaning is quite similar

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/afd/index.md
> +\frac{(\text{slashing rate} * \text{validator bonded stake})}{\text{slashing rate scale factor}}
Ideally it would be better to not have spaces in the formula operands (e.g. "slashingRate" instead of "slashing rate"). Spaces might be interpreted as multiplication between two variables.

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/afd/index.md
> +$$
Don't know why but this shows up as italic in the rendered docs

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/afd/index.md
> +- `High`: severity `2`
```suggestion
- `High`: severity `3`
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/afd/index.md
>  The table below lists each of the rules defined in the AFD rule engine, identified by a unique Rule ID.
Probably better to move this down, before the actual table?

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/afd/index.md
> +Rules are assigned a severity rating according to the risk that failure to adhere to the rule brings to blockchain finality and integrity. The severity taxonomy is:
We also consider the "intentionality" of the fault to determine the severity (i.e. is it possible that this fault has been committed by mistake, or it is a clear malicious behaviour)

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/client/index.md
> +- _Autonity Accountability Contracts_, the accountable and omission fault detection protocol contracts providing operations for: detecting consensus rule infractions and failure to participate in con
```suggestion
- _Autonity Accountability Contracts_, the accountable and omission fault detection protocol contracts providing operations for: detecting consensus rule infractions and failure to participate in consensus voting rounds, and computing rewards and penalties to incentivise correct and disincentivise incorrect behavior [by committee members](/concepts/consensus/committee/). See [Autonity Accountability Contract](/concepts/architecture/#autonity-accountability-contract), [Autonity Omission Accountability Contract](/concepts/architecture/#autonity-omission-accountability-contract) and concepts [Accountability fault detection (AFD)](/concepts/afd/) and [Omission fault detection (OFD)](/concepts/ofd/).
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/protocol-assets/liquid-newton/index.md
> +Note that Liquid Newton is not minted for stake delegations bonded by [autobonding](/glossary/#autobond) of
```suggestion
Note that Liquid Newton is not minted for [autobonding](/glossary/#autobond) of 
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/protocol-assets/newton/index.md
> +The total supply of Newton will be set to 100 million NTNs. 40% of the total supply is set aside as an "inflation reserve" for [inflation rewards](/glossary/#inflation-rewards) released into circulat
```suggestion
The total supply of Newton will be set to 100 million NTNs. 40% of the total supply is set aside as an "inflation reserve" for [inflation rewards](/glossary/#inflation-rewards) released into circulation over the short-to-medium term. Inflation rewards are emitted in the form of newton inflation, i.e. newly minted newton supply, for bonded stake [participating](/glossary/#participation-rate) in securing the [Autonity network](/glossary/#autonity-network). The quantity of newton emissions declines (in average) over time and asymptotically approaches zero.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on glossary/index.md
> +The participation rate is a key dimension of the network’s security, as it quantifies the slashing cost to an attacker successfully launching a $1/3$ superminority attack. A higher participation rate
This sentence is not clear to me. I think the participation rate influences the cost for an attacker to buy 1/3 of the bonded stake, however it does not influence slashing

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/protocol-assets/newton/index.md
> +Please note that in the graph above, the y-axis percentage returns assume a 100% [participation rate](/glossary/#participation-rate) (i.e. all tokens are staked). To model for yourself the expected i
```suggestion
Please note that in the graph above, the y-axis percentage returns assume a 100% [participation rate](/glossary/#participation-rate) (i.e. all tokens are staked). To model for yourself the expected inflation yield, divide the value on the y-axis by an estimated participation rate (e.g. 0.7 for an expected participation rate of 70%, resulting in an inflation yield of 14.3% at genesis for an inflation rate of 10%).
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/protocol-assets/newton/index.md
> +![Figure 1, example inflation curve. Note that parameters are purely illustrative and the Mainnet curve will likely change.](./images/example-inflation-curve.png)
x axis of this image is cut

2025-04-11 13:29 UTC, lorenzo-dev1 commented on node-operators/install-aut/index.md
> +**If you are operating a validator node, then you will need to open the ports for both transactin and consensus gossiping channels to incoming traffic. See [separate channels for transaction and cons
```suggestion
**If you are operating a validator node, then you will need to open the ports for both transaction and consensus gossiping channels to incoming traffic. See [separate channels for transaction and consensus gossiping](/concepts/system-model/#separate-channels-for-transaction-and-consensus-gossiping) for more detail.**
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on overview/index.md
> +  - [Accountable fault detection (AFD)](/concepts/afd/): a protocol for detecting infractions of consensus rules by validators participating in block proposal and voting as a committee member. Failur
```suggestion
  - [Accountable fault detection (AFD)](/concepts/afd/): a protocol for detecting infractions of consensus rules by committee members. Failure to adhere to these rules is a rule infraction and AFD will detect and apply slashing penalties for proven rule infractions.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on overview/index.md
> +  - [Omission fault detection (OFD)](/concepts/ofd/): a protocol for detecting failure to vote in [consensus rounds](/concepts/consensus/pos/#consensus-round-and-internal-state) by a committee member
```suggestion
  - [Omission fault detection (OFD)](/concepts/ofd/): a protocol for detecting failure to vote in [consensus rounds](/concepts/consensus/pos/#consensus-round-and-internal-state) by a committee member and the failure of block proposers to provide activity proofs in block headers [when required](/concepts/ofd/#delta-delta). Failure to participate is a loss of liveness and OFD will detect and apply slashing penalties for proven inactivity.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on overview/index.md
> +- [Oracle network](/concepts/oracle-network/): a protocol for consensus-computed median price data for selected FX currency pairs as an L1 platform feature. The submission of price data for aggregati
I think it could be a bit rephrased to pass the message that only active committee members are allowed to vote. 

However I do agree that all active validators (even the ones outside the committee) should have an oracle running, so that if they are selected they are ready.

Maybe it is sufficient to add something like "Only current committee members are allowed to vote".

2025-04-11 13:29 UTC, lorenzo-dev1 commented on overview/index.md
> +- [Oracle accountability and fault detection (OAFD)](/concepts/oafd/): a protocol for detecting infractions of consensus rules by validator oracles participating in oracle voting rounds and price rep
```suggestion
- [Oracle accountability and fault detection (OAFD)](/concepts/oafd/): a protocol for detecting misbehaving oracles, which will be filtered via outlier detection and slashed accordingly.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on overview/index.md
> +- [Oracle accountability and fault detection (OAFD)](/concepts/oafd/): a protocol for detecting infractions of consensus rules by validator oracles participating in oracle voting rounds and price rep
I rephrased a bit, because it seemed like the OAFD had something to do with consensus rules, but it is not the case.

2025-04-11 13:29 UTC, lorenzo-dev1 commented on overview/index.md
> +  - [Oracle accountability fault detection protocol (OAFD)](/concepts/oafd/) for failing to submit accurate price reports to the oracle protocol on-chain.
```suggestion
  - [Oracle accountability fault detection protocol (OAFD)](/concepts/oafd/) for failing to submit accurate price reports to the oracle on-chain contract.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on overview/index.md
> +| [Oracle accountability fault detection protocol (OAFD)](/concepts/oafd/) | A protocol for detecting failure to submit accurate price reports to the oracle protocol on-chain by validators participat
```suggestion
| [Oracle accountability fault detection protocol (OAFD)](/concepts/oafd/) | A protocol for detecting failure to submit accurate price reports to the oracle on-chain contract by validators participating in consensus as _consensus committee_ members. |
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on reference/api/liquid-newton/index.md
> +Computes the total rewards owed to the validator treasury from commission charged on [delegated](/glossary/#delegated) stake, and sends the appropriate amount of auton to the validator's  `treasury`
Reward computation doesn't happen in this function, but rather when the AC calls `redistribute`.
```suggestion
Sends to the treasury the ATN rewards accrued by the validator via the commission charged on [delegated](/glossary/#delegated) stake.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on reference/api/liquid-newton/index.md
> +The rewards are claimed and sent to the validator's `treasury` by the validator operator calling [`claimTreasuryATN()`](/reference/api/liquid-newton/#claimtreasuryatn).
```suggestion
The rewards can be claimed and sent to the validator's `treasury` by the validator operator calling [`claimTreasuryATN()`](/reference/api/liquid-newton/#claimtreasuryatn).
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on reference/api/liquid-newton/index.md
> +Queries the contract and returns the total rewards owed to a given account.
```suggestion
Queries the contract and returns the total ATN rewards owed to a given account.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on oracle/run-oracle/index.md
> +Oracle prices are submitted with a _confidence score_ in the range $(0, 100)$ expressing the oracle's level of trust in the provided price (For detail on confidence score, see the concept description
```suggestion
Oracle prices are submitted with a _confidence score_ in the range $(0, 100]$ expressing the oracle's level of trust in the provided price (For detail on confidence score, see the concept description [Oracle accountability fault detection (OAFD)](/concepts/oafd/#confidence-score).
```
100 confidence is allowed

2025-04-11 13:29 UTC, lorenzo-dev1 commented on oracle/run-oracle/index.md
> +2. Build the plugin. If building oracle server from binary, then customise the plugin before running `make autoracle`. Alternatively, build the plugin individually a describ ed in [/plugins/README, B
Not sure if this has already been addressed, but this should definitely be a config parameter. Asking node operators to modify the source code and recompile is not ideal.

2025-04-11 13:29 UTC, lorenzo-dev1 commented on oracle/run-oracle/index.md
> +2. Build the plugin. If building oracle server from binary, then customise the plugin before running `make autoracle`. Alternatively, build the plugin individually a describ ed in [/plugins/README, B
```suggestion
Customise the `crypto_uniswap`plugin:

1. Edit the [`defaultConfig`](https://github.com/autonity/autonity-oracle/blob/v0.2.3/plugins/crypto_uniswap/crypto_uniswap.go#L26) in the source golang file must be edited to change:

    - [`defaultConfig.Endpoint`](https://github.com/autonity/autonity-oracle/blob/v0.2.3/plugins/crypto_uniswap/crypto_uniswap.go#L28): change the `endpoint` to replace the `rpc1-internal` endpoint with the endpoint address of their own connected validator node.
    - [`defaultConfig.Scheme`](https://github.com/autonity/autonity-oracle/blob/v0.2.3/plugins/crypto_uniswap/crypto_uniswap.go#L29): update to the scheme used for the endpoint (http/s or ws/s).

2. Build the plugin. If building oracle server from source, then customise the plugin before running `make autoracle`. Alternatively, build the plugin individually as described in [/plugins/README, Build it](https://github.com/autonity/autonity-oracle/blob/v0.2.3/plugins/README.md#build-it). In the `autonity-oracle` directory run:
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on oracle/run-oracle/index.md
> +If a simulator has been deployed and is available to provide simulated data for testnet use, this can be connected to by adding a config entryfor the simulated source to your `plugins-conf.yml` file.
```suggestion
If a simulator has been deployed and is available to provide simulated data for testnet use, this can be connected to by adding a config entry for the simulated source to your `plugins-conf.yml` file.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on oracle/run-oracle/index.md
> +If you are setting up or connecting to a local Autonity testnet an ATN and NTN Simulator plugin is available.
I feel like this sentence could be removed, i am not really sure what it tries to communicate

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +	- **Accountability Contracts** implementing protocol primitives for accountable and omission fault detection for validators participating in the consensus committee. Accountability covers participat
```suggestion
	- **Accountability Contracts** implementing protocol primitives for accountable and omission fault detection for validators participating in the consensus committee. The consensus accountability protocol enforces validator liveness and adherence to the [Tendermint consensus](/concepts/consensus/pos/) rules, implementing slashing penalties and a [Penalty-Absorbing Stake (PAS)](/concepts/afd/#penalty-absorbing-stake-pas) model.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +	- **Accountability Contracts** implementing protocol primitives for accountable and omission fault detection for validators participating in the consensus committee. Accountability covers participat
Since the next sentence about the oracle protocol also mentions accountability, I think we can omit it here.

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +	- **Auton Stabilization Mechanism Contracts** implementing a [Stabilization Mechanism](/concepts/asm/) for the protocol's native coin [Auton](/concepts/protocol-assets/auton/) via a Collateralized D
```suggestion
	- **Auton Stabilization Mechanism Contracts** implementing a [Stabilization Mechanism](/concepts/asm/) for the protocol's native coin [Auton](/concepts/protocol-assets/auton/) via a Collateralized Debt Position (CDP). Changes in supply and demand for Auton are absorbed by dynamically adjusting CDP incentives to increase and decrease Auton borrowing costs when Auton price moves above or below its Stabilization Target the [Autonomous Currency Unit (ACU)](/glossary/#acu).
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +Inflation rewards accumulate from the Newton inflation mechanism and awarded for Newton stake token that is delegated to validators. The emissions are:
something missing here

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +- Computed for delegated stake according to the Newton [inflation mechanism](/glossary/#inflation-mechanism) (note that _all_ delegated stake earns inflation rewards - there is no dependency on stake
Also self-bonded stake gets inflation rewards autobonded. Also the part in the "(...)" is incorrect, inflation rewards are given only to stake which is currently in the committee

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +- The Newton inflation emission is minted from the [inflation reserve](/glossary/#inflation-mechanism) and [automatically bonded](/glossary/#autobond) Block _base fees_ are added to the rewards pool
```suggestion
- The Newton inflation emission is minted from the [inflation reserve](/glossary/#inflation-mechanism) and [automatically bonded](/glossary/#autobond). Block _base fees_ are added to the rewards pool and distributed at the end of the epoch.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +Function calls to compute accountability each block and apply accountability penalties at epoch end are restricted to protocol.
```suggestion
Function calls to compute accountability at each block and apply accountability penalties at epoch end are restricted to protocol.
```

"at " missing I guess

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +Function calls to detect validator inactivity each block and apply omission penalties at epoch end are restricted to protocol.
```suggestion
Function calls to detect validator inactivity at each block and apply omission penalties at epoch end are restricted to protocol.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +The Autonity Omission Accountability Contract implements logic for measuring if a consensus committee is actively participating in consensus voting rounds as a committee member:
```suggestion
The Autonity Omission Accountability Protocol implements logic for measuring if a committee member is actively participating in consensus voting rounds:
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +- Measures validator activity by recording committee member precommit messages as a cryptographically-verifiable BLS aggregate signature as an $ActivityProof$ generated by the block proposer and incl
```suggestion
- Measures validator activity by recording precommit messages as a cryptographically-verifiable BLS aggregate signature ($ActivityProof$) generated by the block proposer and included in the block headers.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +- Maintains an inactivity score for committee members during the epoch, computed as an offline percentage of blocks in an epoch that the validator has failed to participate in consensus for.
```suggestion
- Maintains an inactivity score for committee members during the epoch, computed as a percentage of blocks in an epoch that the validator has failed to participate in consensus for.
```

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +- Calculate penalties based on static (set in the contract, see [protocol configuration](/concepts/ofd/#protocol-configuration)) and dynamic factors specific to the epoch circumstances. See [slashing
I am not sure if it is because this docs is based on the previous release, but currently I believe that all parameters of the omission contract can be changed (i.e. there are no static parameters).

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +- Apply slashing and permanent jailing if repeat offending while on probation. See [Slashing amount calculation](/concepts/ofd/#slashing-amount-calculation). Slashing is applied according to Autonity
```suggestion
- Apply slashing and longer jailing if repeated offences are committed while on probation. See [Slashing amount calculation](/concepts/ofd/#slashing-amount-calculation). Slashing is applied according to Autonity's [Penalty-Absorbing Stake (PAS)](/concepts/afd/#penalty-absorbing-stake-pas) model: validator self-bonded stake is slashed first until exhausted, then delegated stake.
```

Jailbounding is really just an edge case for when we end up slashing 100%

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +- Static [protocol configuration](/concepts/oafd/#protocol-configuration) used to compute slashing penalties.
Which part of the config is the static part you are referring to?

2025-04-11 13:29 UTC, lorenzo-dev1 commented on concepts/architecture/index.md
> +- [Protocol parameters](/reference/protocol/) for median price computation and oracle voting rounds. These specify the currency pairs for which the oracle provides median price data, the interval ove
the price we end up providing is not really a median, but rather a weighted average which uses the confidence as weight. The median is used only for outlier detection.

2025-04-14 10:55 UTC, cmjc commented on concepts/afd/index.md
> +Rules are assigned a severity rating according to the risk that failure to adhere to the rule brings to blockchain finality and integrity. The severity taxonomy is:
OK. I was trying to keep this simple by just phrasing as blockchain finality and integrity. Hmm. Does this rewording capture this aspect?

>Rules are assigned a severity rating according to (a) the risk that failure to adhere to the rule brings to blockchain finality and integrity, (b) if the fault is accidental or Byzantine in nature. 

That is very simple.

2025-04-14 10:57 UTC, cmjc commented on glossary/index.md
Yes, agree.

2025-04-14 11:10 UTC, cmjc commented on reference/api/liquid-newton/index.md
> +The rewards are claimed and sent to the validator's `treasury` by the validator operator calling [`claimTreasuryATN()`](/reference/api/liquid-newton/#claimtreasuryatn).
That changes it from the active to the passive voice, and it's best practice to use passive:

https://developers.google.com/tech-writing/one/active-voice

Resolving.

2025-04-14 11:18 UTC, cmjc commented on oracle/run-oracle/index.md
> +2. Build the plugin. If building oracle server from binary, then customise the plugin before running `make autoracle`. Alternatively, build the plugin individually a describ ed in [/plugins/README, B
FYSA @Jason-Zhangxin-Chen 

@lorenzo-dev1 - it's current state so the docs should reflect that state.

Can you create this as an issue in the autonity-oracle repo and resolve here?

Then, the docs can be updated once the issue is resolved.

2025-04-14 11:20 UTC, cmjc commented on oracle/run-oracle/index.md
> +2. Build the plugin. If building oracle server from binary, then customise the plugin before running `make autoracle`. Alternatively, build the plugin individually a describ ed in [/plugins/README, B
But there is an extra space and typo that needs correcting:

>...build the plugin individually a describ ed ...

That should be 'as described'

2025-04-14 11:21 UTC, cmjc commented on oracle/run-oracle/index.md
> +2. Build the plugin. If building oracle server from binary, then customise the plugin before running `make autoracle`. Alternatively, build the plugin individually a describ ed in [/plugins/README, B
Which typo then got fixed in the following comment.

2025-04-14 13:51 UTC, cmjc commented on concepts/oracle-server/index.md
> +
Hi @Jason-Zhangxin-Chen I have edited this note to add the Piccadilly Tstnet setup as you ask:

>ATN-NTN price data for [Piccadilly Testnet](/networks/testnet-piccadilly/) is computed using mock 'USDCx'. Piccadilly Testnet validators can retrieve ATN-USDCx and NTN-USDCx price data from a Uniswap V2 AMM clone deployed on the testnet using the `crypto_uniswap` plugin. For how to configure this see the Guide _Running an Oracle Server_ and [Setup crypto plugin config](/oracle/run-oracle/#setup-crypto-plugin-config).

2025-04-14 13:53 UTC, jay-cousins commented on concepts/oracle-server/index.md
> +
See commit 49a62108013dcc65946d94c8bfef4364e32776e8

2025-04-14 14:03 UTC, jay-cousins commented on concepts/oafd/index.md
> +#### Price report
@Jason-Zhangxin-Chen Clarified by adding this to the fifth paragraph in the section.

See commit:  32f844bb6e82d6ecdaf8f608679b86d67d56a09f

2025-04-14 15:56 UTC, jay-cousins commented on glossary/index.md
Merged voting period into vote period. Merged in commit 7f4d5b56c4be3f5a129922c3d30d893cd6ba18d6 vote period.

(Included check to update docs hyperlinks to 'voting period' and repoint to 'vote period'.)

2025-04-14 16:18 UTC, jay-cousins commented on glossary/index.md
> +See [delegated](/glossary/#delegated) and [self-bonded](/glossary/#self-bonded).
Clarified in commit 6121df5f349d642623659b2b2952b5cdc32c51e1

2025-04-16 08:58 UTC, cmjc commented on concepts/oracle-server/index.md
> +
@Jason-Zhangxin-Chen - can this be resolved?

2025-04-16 08:58 UTC, cmjc commented on concepts/oafd/index.md
> +#### Price report
@Jason-Zhangxin-Chen - can this be resolved?

2025-04-16 10:28 UTC, cmjc commented on glossary/index.md
> +Newton is not redeemed to the stake [delegator](/glossary/#delegation) until the end of the [epoch](/glossary/#epoch) in which the unbonding period expires.
Edited in commit 2c1d4e660ca3e38b3120d398a36a1eaa0e23bde6. Note I've reviewed all references to redemption in the glossary and where it remains it is I think OK as mint/burn is subsequently mentioned where appropriate.

2025-04-16 13:09 UTC, cmjc commented on concepts/afd/index.md
> +$$
Ah, the wrapping `\text{` `}` was missing! Fixed. And changed to concatenate per preceding comment

```
$$
\text{currentBlockNumber + jailFactor * history * epochPeriod}
$$
```

2025-04-16 13:16 UTC, cmjc commented on concepts/afd/index.md
> +\frac{(\text{slashing rate} * \text{validator bonded stake})}{\text{slashing rate scale factor}}
Makes sense. Corrected in commit ce0f47c648678159850daad6b6bd9af89c1f61f5.

2025-04-16 13:16 UTC, cmjc commented on concepts/afd/index.md
> +$$
Corrected in commit ce0f47c648678159850daad6b6bd9af89c1f61f5.

2025-04-16 13:16 UTC, cmjc commented on concepts/afd/index.md
>  The table below lists each of the rules defined in the AFD rule engine, identified by a unique Rule ID.
Yes, moved. Commit ce0f47c648678159850daad6b6bd9af89c1f61f5.

2025-04-16 13:16 UTC, cmjc commented on concepts/afd/index.md
> +Rules are assigned a severity rating according to the risk that failure to adhere to the rule brings to blockchain finality and integrity. The severity taxonomy is:
Done in commit ce0f47c648678159850daad6b6bd9af89c1f61f5.

2025-04-16 15:15 UTC, cmjc commented on glossary/index.md
> +The participation rate is a key dimension of the network’s security, as it quantifies the slashing cost to an attacker successfully launching a $1/3$ superminority attack. A higher participation rate
That should be staking cost not slashing cost.  The slashing risk is proportional to the amount staked, so it quantifies both for the attacker.

Reword to:

>The participation rate is a key dimension of the network’s security. It quantifies the staking cost for an attacker attempting to launch a $1/3$ superminority attack, and the slashing cost when detected. A higher participation rate results in higher economic security.

Perhaps should just remove ", and the slashing cost when detected" - less is more?

2025-04-16 15:16 UTC, cmjc commented on glossary/index.md
> +The participation rate is a key dimension of the network’s security, as it quantifies the slashing cost to an attacker successfully launching a $1/3$ superminority attack. A higher participation rate
Commit ba86caa121008b2e55420a953d031989d7ebb730

2025-04-16 15:19 UTC, jay-cousins commented on concepts/protocol-assets/newton/index.md
> +Please note that in the graph above, the y-axis percentage returns assume a 100% [participation rate](/glossary/#participation-rate) (i.e. all tokens are staked). To model for yourself the expected i
Corrected. Resolving.

2025-04-16 15:30 UTC, cmjc commented on overview/index.md
> +- [Oracle network](/concepts/oracle-network/): a protocol for consensus-computed median price data for selected FX currency pairs as an L1 platform feature. The submission of price data for aggregati
Reworded to clarify to:

>- [Oracle network](/concepts/oracle-network/): a protocol for consensus-computed weighted average price data for selected FX currency pairs as an L1 platform feature. The submission of price data for aggregation and voting is a validator responsibility. Validators form an oracle network, with each validator node running an [oracle server](/concepts/oracle-server) to source price data. Only consensus committee members participate in oracle [voting rounds](/concepts/oracle-network/#voting-rounds).

Commit ed512d525f39260dc7526c43ea2aa404965c0a3a

2025-04-16 15:36 UTC, cmjc commented on oracle/run-oracle/index.md
> +If you are setting up or connecting to a local Autonity testnet an ATN and NTN Simulator plugin is available.
To make it clear to a user when you use the simulator - in a testnet scenario, either on a public testnet or in your own local testnet.

Removed. b6441d159c2d882af8c4174b1d91495014be3598

2025-04-16 15:45 UTC, cmjc commented on concepts/architecture/index.md
> +Inflation rewards accumulate from the Newton inflation mechanism and awarded for Newton stake token that is delegated to validators. The emissions are:
Yes, this should be re-written to:

>Inflation rewards accumulate from the Newton inflation mechanism and are awarded for Newton stake token that has been delegated to validators.

2025-04-16 15:58 UTC, cmjc commented on concepts/architecture/index.md
> +- Computed for delegated stake according to the Newton [inflation mechanism](/glossary/#inflation-mechanism) (note that _all_ delegated stake earns inflation rewards - there is no dependency on stake
I agree looking at the code, though I was told otherwise. I will change this so:

>Inflation rewards accumulate from the Newton inflation mechanism and are awarded for Newton stake token that has been delegated to validators in the consensus committee. The emissions are:
>
>- Computed for stake bonded to the consensus committee members according to the Newton [inflation mechanism](/glossary/#inflation-mechanism) (note inflation rewards are _only_ earned for stake actively securing the network - stake delegations to validators that _are not_ in the current consensus committee _will not_ earn inflation rewards).

Commit: 0331489abdd49ad0ec1c61a194952ade8ccb73d9

2025-04-16 16:01 UTC, cmjc commented on concepts/protocol-assets/newton/index.md
> +![Figure 1, example inflation curve. Note that parameters are purely illustrative and the Mainnet curve will likely change.](./images/example-inflation-curve.png)
This shouldn't be a blocker as it is an example. It will need to be updated with the real one for the next PR.

2025-04-16 16:21 UTC, jay-cousins commented on concepts/architecture/index.md
> +- Calculate penalties based on static (set in the contract, see [protocol configuration](/concepts/ofd/#protocol-configuration)) and dynamic factors specific to the epoch circumstances. See [slashing
Hmm. It is static as it is set and remains until it is changed, but I see the point. Hmm.

Will remove the static and rely on protocol config. Revised so:

>Calculate penalties based on parameters set in the [protocol configuration](/concepts/ofd/#protocol-configuration) and dynamic factors specific to the epoch circumstances

Done in commit 769e9c24eb1b3ee1bab3627614dd7bbb5ef77662

2025-04-16 16:21 UTC, cmjc commented on concepts/architecture/index.md
> +- Calculate penalties based on static (set in the contract, see [protocol configuration](/concepts/ofd/#protocol-configuration)) and dynamic factors specific to the epoch circumstances. See [slashing
I reviewed the whole page for 'static' and fixed in the same commit 769e9c24eb1b3ee1bab3627614dd7bbb5ef77662.

2025-04-16 16:22 UTC, cmjc commented on concepts/architecture/index.md
> +- Static [protocol configuration](/concepts/oafd/#protocol-configuration) used to compute slashing penalties.
See preceding comment thread on static and change made https://github.com/autonity/docs.autonity.org/pull/259#discussion_r2035642861

Fixed in commit 769e9c24eb1b3ee1bab3627614dd7bbb5ef77662.

2025-04-16 16:30 UTC, cmjc commented on concepts/architecture/index.md
> +- [Protocol parameters](/reference/protocol/) for median price computation and oracle voting rounds. These specify the currency pairs for which the oracle provides median price data, the interval ove
Yes, need to replace 'median price' with 'weighted average'. Reviewed and corrected throughout the section, median only remains in relation to outlier detection.

See commit 79c5b3485b1bb1e4be717030e29ca7def6af6a58

2025-04-16 16:34 UTC, jay-cousins commented on concepts/protocol-assets/newton/index.md
> +![Figure 1, example inflation curve. Note that parameters are purely illustrative and the Mainnet curve will likely change.](./images/example-inflation-curve.png)
So, I think this can be resolved.

2025-04-16 16:37 UTC, jay-cousins commented on concepts/architecture/index.md
> +Inflation rewards accumulate from the Newton inflation mechanism and awarded for Newton stake token that is delegated to validators. The emissions are:
Done in commit: https://github.com/autonity/docs.autonity.org/commit/0331489abdd49ad0ec1c61a194952ade8ccb73d9.

2025-04-17 07:31 UTC, lorenzo-dev1 commented on oracle/run-oracle/index.md
> +2. Build the plugin. If building oracle server from binary, then customise the plugin before running `make autoracle`. Alternatively, build the plugin individually a describ ed in [/plugins/README, B
issue created https://github.com/autonity/autonity-oracle/issues/58, solving this thread then.

2025-04-17 09:57 UTC, Jason-Zhangxin-Chen commented on oracle/run-oracle/index.md
> +2. Build the plugin. If building oracle server from binary, then customise the plugin before running `make autoracle`. Alternatively, build the plugin individually a describ ed in [/plugins/README, B
> FYSA @Jason-Zhangxin-Chen
> 
> @lorenzo-dev1 - it's current state so the docs should reflect that state.
> 
> Can you create this as an issue in the autonity-oracle repo and resolve here?
> 
> Then, the docs can be updated once the issue is resolved.

Those are default configs, people can config them from the config file by adding: 
```yaml
# Un-comment below lines to config the RPC endpoint of a Piccadilly Network Full Node for your AMM plugin which sources ATN & NTN market data from an on-chain AMM.
#  - name: crypto_uniswap
#    scheme: "wss"                                          # Only websocket please, available values are: "ws" or "wss", default value is "wss" for uniswap plugins.
#    endpoint: "rpc-internal-1.piccadilly.autonity.org/ws"  # The default URL might not be stable for public usage, we recommend you to change it with your validator node's RPC endpoint.
```

2025-04-17 14:52 UTC, lorenzo-dev1 requested changes
The docs has become really informative. I left some comments to polish things up more and make some parts of it more precise.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on glossary/index.md
> +During the vote period [Autonity oracles](/glossary/#autonity-oracle-server-aos) collect price data from data providers and submit price data reports on-chain for [currency pair](/glossary/#currency-
median --> weighted average

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/protocol/index.md
> +| `1`          | 0.001% slash |
```suggestion
| `10`         | 0.1% slash |
| `1`          | 0.01% slash |
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/protocol/index.md
> +| `initialJailingPeriod` | The initial number of epoch(s) that a validator will be jailed for | Set by default to `10_000` (10000 blocks) | See [`setInitialJailingPeriod()`](/reference/api/aut/op-pro
```suggestion
| `initialJailingPeriod` | The initial number of block(s) that a validator will be jailed for | Set by default to `10_000` (10000 blocks) | See [`setInitialJailingPeriod()`](/reference/api/aut/op-prot/#setinitialjailingperiod-omission-accountability-contract) |
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/protocol/index.md
> +| `initialSlashingRate` | The division precision used as the denominator when computing the slashing amount of a penalty | Set by default to `25` (0.25%) | See [`setInitialSlashingRate()`](/reference
This parameter is not really the precision, it is the starting slashing rate on top of which we build up the full slashing rate

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/genesis/index.md
> +| `abi` | The abi of an upgraded Autonity Oracle Contract to be deployed at genesis. By default the Autonity Oracle Contract in the Autonity Go Client release is deployed. Only specify if overriding
I think this is for the autonity contract, not for the oracle one

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/api/web3/index.md
> +Recommended usage is to make JSON-RPC calls to Autonity Contract Interfaces using `eth_call` from the Web3 [eth namespace](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-eth) wherever po
```suggestion
Recommended usage is to make JSON-RPC calls to Autonity Contract Interfaces using `eth_call` from the Web3 [eth namespace](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-eth) wherever possible.
```

That part I feel like is more for the developers rather than end users

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/api/liquid-newton/index.md
> +The rewards are claimed and sent to the validator's `treasury` by the validator operator calling [`claimTreasuryATN()`](/reference/api/liquid-newton/#claimtreasuryatn).
@cmjc  my point is that using `are` suggests that no action is required from the user. While instead claiming rewards is something the user needs to actively do.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/api/web3/index.md
> +:::
Also here I would switch from sentences like: 
```
The HTTP and WebSocket Servers are enabled and the JSON-RPC namespaces to be made accessible listed using run command flags:
```

to 

```
The HTTP and WebSocket Servers, and the related JSON-RPC namespaces, can be made accessible using run command flags:
```

The active voice gives me the impression that it is a default behaviour, while instead it is something where the user needs to actively make a decision.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/api/web3/index.md
> +:::
There are multiple instances of this issue in this paragraph.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/api/oracle/index.md
> +Prices for currency symbols in oracle server price data reports are aggregated off-chain and computed to a price precision determined by the [Oracle protocol](/concepts/oracle-network/#oracle-protoco
```suggestion
Prices for currency symbols in oracle server price data reports are aggregated off-chain and computed to a price precision determined by the [Oracle protocol](/concepts/oracle-network/#oracle-protocol) decimal places configuration (i.e. `18`). However, the price reports are submitted on-chain for price aggregation in the Oracle Contract as integer values. When requesting the price of a symbol on-chain from the Oracle Contract, therefore, the price point is returned as an integer value without precision.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/api/omission-accountability/index.md
> +Usage and Examples assume the path to the ABI file has been set in `aut`'s configuration file `.autrc`. The `Accountability.abi` file is generated when building the client from source and can be foun
```suggestion
Usage and Examples assume the path to the ABI file has been set in `aut`'s configuration file `.autrc`. The `OmissionAccountability.abi` file is generated when building the client from source and can be found in your `autonity` installation directory at `./params/generated/OmissionAccountability.abi`. Alternatively, you can generate the ABI using the `abigen` `cmd` utility if you built from source (See [Install Autonity, Build from source code](/node-operators/install-aut/#install-source)).
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/api/aut/index.md
> +To return an ERC2-0 contract token (e.g. Liquid Newton) balance for an account specify the `--token` option:
```suggestion
To return an ERC-20 contract token (e.g. Liquid Newton) balance for an account specify the `--token` option:
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/api/aut/index.md
> +Total supply is the total amount of Newton that has been minted. Circulating supply is simply the total supply minus the sum of any minted NTN that is locked and released into circulation over time b
```suggestion
Total supply is the total amount of Newton that has been minted. Circulating supply is simply the total supply minus the sum of any minted NTN that is locked and released into circulation over time according to a schedule.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/api/aut/op-prot/index.md
> +Creates a new schedule for a non-stakeable vesting contract, specifying how much Newton is to be locked, twhen the schedule will begin to release Newton into circulation, and the total duration of th
```suggestion
Creates a new schedule for a non-stakeable vesting contract, specifying how much Newton is to be locked, when the schedule will begin to release Newton into circulation, and the total duration of the locking schedule.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/api/aut/op-prot/index.md
> +- the `low` slashing rate cannot exceed the `high` slashing rate
```suggestion
- the `low` slashing rate cannot exceed the `mid` slashing rate
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on reference/api/aut/op-prot/index.md
> +- a `Rewarded` event for each staking reward distribution, logging: recipient address `addr`, `atnAmount`m `ntnAmount`.
```suggestion
- a `Rewarded` event for each staking reward distribution, logging: recipient address `addr`, `atnAmount` and `ntnAmount`.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/staking/index.md
> +Newton inflation rewards are distributed to [participating](/glossary/#participation-rate) stake at the end of each epoch by the Newton [inflation mechanism](/glossary/#inflation-mechanism). The newt
The last sentence needs to be changed, since inflation rewards are given to active committee members only

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/staking/index.md
> +[Newton inflation](/concepts/protocol-assets/newton/#total-supply-and-newton-inflation) emissions for delegated stake are [autobonded](/glossary/#autobond) by protocol.
```suggestion
[Newton inflation](/concepts/protocol-assets/newton/#total-supply-and-newton-inflation) rewards are [autobonded](/glossary/#autobond) by protocol.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/staking/index.md
> +Alice submits a [`bond()`](/reference/api/aut/#bond) tx that is processed and included in a block at time $T$, where a `BondingRequest` object for the necessary voting power change is also created. N
```suggestion
Alice submits a [`bond()`](/reference/api/aut/#bond) tx that is processed and included in a block at time $T$, where a `BondingRequest` object for the necessary voting power change is also created. Newton is burnt at $T$.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/staking/index.md
> +The bonding request is tracked in memory for application at the end of the epoch in which $T$ was processed. At this point, the validator's bonded stake is increased, and Liquid Newton is issued to A
I feel like the last two sentences could be moved in the previous paragraph, since they refer to the period of time in between bonding tx being mined and the epoch's ending.

Or we could even straight out remove them.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/validator/index.md
> +    6.b. Permanent jailing: `jailbound` or `jailboundForInactivity` state. In this state the validator is *permanently* jailed and becomes [jailbound](/glossary/#jailbound). Permanent jailing is only
The omission accountability part is a bit imprecise, as committing an inactivity fault while on probation doesn't necessarily imply being slashed 100% and therefore jailbound. One would need to commit offences multiple times while on probation to reach 100% slash. It is an extreme case.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/validator/index.md
> +  - Newton [inflation rewards](/glossary/#inflation-rewards) accrue to all bonded stake irrespective of whether it is active in the current consensus committee or not. [Delegated](/glossary/#delegate
Also here the first sentence needs to be corrected.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/validator/index.md
> +  - This is in contrast to [staking rewards](/glossary/#staking-rewards) where staking rewards are only earned when the validator bonded to is active in the current consensus committee. The stakers w
And this one as well since it relates to the previous one.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/validator/index.md
> +  - [AFD rewards](/concepts/afd/#slashing-rewards) earned for reporting slashed faults.
```suggestion
  - [AFD rewards](/concepts/afd/#slashing-rewards) earned for reporting faults.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/validator/index.md
> +- On permanent jailing the validator enters a `jailbound` or `jailboundForInactivity` state and is *permanently* jailed. It becomes [jailbound](/glossary/#jailbound) and cannot get out of jail. Perma
Last part about OFD is imprecise, as explained in a previous comment.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +Autonity implements an _omission fault detection_ (OFD) protocol for detecting if [consensus committee](/glossary/#consensus-committee) members are _actively_ participating in [consensus](/glossary/#
```suggestion
Autonity implements an _omission fault detection_ (OFD) protocol for detecting if [consensus committee](/glossary/#consensus-committee) members are _actively_ participating in [consensus](/glossary/#consensus) voting rounds. To ensure the maximum level of network liveness committee members should be online and participating in each [consensus](/glossary/#consensus) voting round. An _inactive committee member_ is a committee member that is failing to do this. To be _inactive_ the validator is either not sending consensus messages when it should (failure to vote) or it is sending consensus messages too late to be included in a consensus round (failure to vote on time). In either scenario the validator is considered to have lost liveness and is deemed _inactive_ by protocol.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +Autonity's [Tendermint BFT consensus](/concepts/consensus/pos/) is coordinated by committee member voting via the broadcasting of consensus messages in a consensus channel in the [communication layer
```suggestion
Autonity's [Tendermint BFT consensus](/concepts/consensus/pos/) is coordinated by committee member voting via the broadcasting of consensus messages in the [communication layer](/concepts/architecture/#communication-layer). It assumes a stable broadcast communication channel and a [semi-synchronous network timing model (_GST & Delta_) for message reception](/concepts/system-model/#networking). The Tendermint algorithm assumes that at _GST + Delta_, all the consensus messages sent at _GST_ should have been received by committee members.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +Autonity's [Tendermint BFT consensus](/concepts/consensus/pos/) is coordinated by committee member voting via the broadcasting of consensus messages in a consensus channel in the [communication layer
I feel like it is better to remove the last sentence as it can cause confusing with the omission delta... I think the previous explaination is enough.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +The OFD protocol is based upon the processing of consensus messages and their timing allowing for the delta latency, therefore. [Consensus committee](/concepts/consensus/committee/) members participa
```suggestion
The OFD protocol is based upon the processing of consensus messages and their timing, allowing for $\Delta$  blocks of latency. [Consensus committee](/concepts/consensus/committee/) members participate in [consensus rounds](/concepts/consensus/pos/#consensus-round-and-internal-state) with block _proposal_, _prevote_, and _precommit_ stages before a block is committed to [system state](/concepts/system-model/#system-state). (See the concept description [Consensus round and internal state](/concepts/consensus/pos/#consensus-round-and-internal-state)). 
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +$\Delta$ is the number of blocks committee members wait for before generating an activity proof. I.e. activity proof for block $x$ is going to be computed at block $x+\Delta$. The $\Delta$ allows for
I understand the message here, however I feel like the part about the fair start of the epoch needs a bit of refactoring.

The fair start of the epoch is not really granted by the usage of delta, but rather by the protocol allowing (and enforcing) empty activity proof for the first delta block of the epoch.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +As noted above the block proposer generates and includes a BLS signature aggregation of _precommit_ signatures of height $h - \Delta$ into the $ActivityProof$ included in the header of $h$. Each bloc
```suggestion
As noted above the block proposer generates and includes a BLS signature aggregation of _precommit_ signatures of height $h - \Delta$ into the $ActivityProof$ included in the header of $h$.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +Autonity uses BLS signature aggregation verification to cryptographically verify which consensus committee members  posted a _precommit_ vote and so _actively_ participated in consensus. A large comm
```suggestion
Autonity uses BLS signature aggregation verification to cryptographically verify which consensus committee members  posted a _precommit_ vote and so are _actively_ participated in consensus. A large committee size is an Autonity design goal for scalability. The BLS curve property of verification efficiency makes it suited use as a signature aggregation algorithm in consensus computation.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +OFD inspects the $ActivityProof$ to determine committee _inactivity_ historically over a block window defined by the OFD protocol configuration parameter $LookbackWindow$. The $ActivityProof$, like a
```suggestion
OFD inspects the $ActivityProof$ to determine committee _inactivity_ historically over a block window defined by the OFD protocol configuration parameter $LookbackWindow$. The $ActivityProof$, like an AFD fault proof, is therefore stored on-chain
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +The Omission Accountability Contract is invoked on each block finalisation to determine inactivity and compute inactivity penalties. Any penalties computed are then tracked in memory for application
```suggestion
The Omission Accountability Contract is invoked on each block finalisation to determine inactivity and compute inactivity scores. Inactivity penalties are computed and applied at epoch end.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +OFD functions, therefore, by submitting, verifying, and processing activity proofs for omission faults captured over a rolling block window by epoch.
I think something is missing here

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +- withholding of OFD proposer fee reward incentives proportionally to the offline % of in the epoch, measured by the % of blocks the validator was offline for in the epoch
there is no withholding on the proposer rewards, the withholding gets applied to:
- the NTN inflation rewards (as correctly mentioned in the following line)
- the ATN epoch fees rewards

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +- withholding of proposer [Newton inflation](/concepts/protocol-assets/newton/#total-supply-and-newton-inflation) rewards proportionally to the offline % of in the epoch, measured by the % of blocks
```suggestion
- withholding of [Newton inflation](/concepts/protocol-assets/newton/#total-supply-and-newton-inflation) rewards proportionally to the offline % of in the epoch, measured by the % of blocks the validator was offline for in the epoch
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +- jailing if the validator's offline % in the epoch is greater than a permitted threshold set by protocol
```suggestion
- jailing and probation if the validator's offline % in the epoch is greater than a permitted threshold set by protocol
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +- stake slashing if the validator is seen as inactive when under probation after repeated jailings.
```suggestion
- stake slashing if the validator is seen as inactive when under probation after being jailed.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +Rewards are paid to block proposers for including as many signatures in the $ActivityProof$ as possible. The _block proposer_ reward is a fraction of transaction fees earned by protocol in the epoch.
```suggestion
Rewards are paid to block proposers for including as many signatures in the $ActivityProof$ as possible. The _block proposer_ reward is a fraction of the epoch rewards. The block proposer's reward amount is computed based on the proposer effort that he provided in the epoch. The proposer effort of an $ActivityProof$ is determined as the voting power of the signatures exceeding the quorum value. ATN rewards are paid to the  _reporting validator_ `treasury` account, while NTN rewards are autobonded.
```

I rephrased this sentence in a more precise way, however I am not convinced of my version as well. Feel free to modify if you come up with something better.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +| _offending_ | as the validator found to be inactive by the OFD and the object of slashing penalties |
```suggestion
| _offender_ | as the validator found to be inactive by the OFD and the object of slashing penalties |
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +The Autonity community is also a _beneficiary_ of OFD processing. Slashed stake token, withheld proposer fee rewards, and withheld Newton inflation rewards will be used for community funds.
ALso here, proposer rewards are never withheld

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +An _activity proof_ is a BLS signature aggregation of committee member _precommit_ votes submitted for a block during a Tendermint consensus voting round. The _block proposer_ includes an _activity p
```suggestion
An _activity proof_ is a BLS signature aggregation of committee member _precommit_ votes submitted for a block during a Tendermint consensus voting round. The _block proposer_ includes an _activity proof_ in the block header and it is validated by the other committee members as part of block validation.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +Each block header contains a historical record of committee activity at block height $h$ is computed at $h + \Delta$ and used for activity signalling.
```suggestion
Each block header $h$ contains a historical record of committee activity at block height $h - \Delta$. This information is used for activity signalling.  
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +The $\Delta$ allows for two temporal factors, epoch periods and the network's semi-synchronous nature. Firstly, it allows for a fair start of an epoch and prevents the _block proposer_ looking for in
This section needs a bit of refactoring. The delta is number of block the validators wait for generating an activity proof (e.g. if delta = 5, then at block 100 the validators will generate the activity proof for block 95). The consequence of that is that the last delta block of an epoch are not accountable, because the proof would theoretically need to be generated at the first delta block of the next epoch.

However this is not possible because the epoch end causes committee re-election.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +If the _activity proof_ is empty past the $\Delta$ period, then this is an _omission fault_ (_offence_) and the _block proposer_ is subject to penalty. The $\Delta$ period is set as a protocol config
```suggestion
If the _activity proof_ is empty past the first $\Delta$ block of the epoch, then this is an _omission fault_ (_offence_) and the _block proposer_ is subject to penalty. The $\Delta$ period is set as a protocol configuration parameter.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +The _lookback window_ is extended by 1 for each empty $ActivityProof$ it includes. I.e. if there are 2 empty $ActivityProof$ in the _lookback window_, $L_{P}' = L_{P} + 2$, with $L_{P}$ being the def
```suggestion
The _lookback window_ is extended by 1 for each empty $ActivityProof$ it includes. I.e. if there are 2 empty $ActivityProof$ in the _lookback window_, $L_{P}' = L_{P} + 2$, with $L_{P}$ being the default value.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +The average offline percentage of a committee member for an epoch is computed as an _inactivity score_. The offline percentage is measured as the % of blocks in an epoch that the validator has failed
```suggestion
The average offline percentage of a committee member for an epoch is computed as an _inactivity score_. The offline percentage is measured as the % of blocks in an epoch that the validator has failed to timely participate in consensus for.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +The _inactivity scores_ for the current and past epoch are aggregated to computes an _aggregated inactivity score_. Penalties are applied only if a committee member's _aggregated inactivity score_ br
The probation period doesn't really affect the slashing rate, but only if the validator will get slashed or not. Also it is worth mentioning that the offence counter gets reset to 0 once the probation period expires without any offence.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +To incentivise liveness OFD sets a _probation period_ measured in epochs. The duration of the _probation period_ for a validator is determined by the protocol's _initial probation period_ configured
```suggestion
To incentivise liveness OFD sets a _probation period_ measured in epochs. The duration of the _probation period_ for a validator is determined by the protocol's _initial probation period_ configured value multiplied by the individual validator's _offence_ count squared. Until the validator has committed a first _offence_ its _probation period_ is nil (`0`) epochs. Once offence count is `>0` the validator is in _probation_ and its _probation period_ will begin to number epochs. As soon as an _offending validator_ completes an entire _probation period_ without offences its _offence_ count is reset to `0`, taking the validator out of _probation_.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +- The _negligible threshold_ sets a floor which if broken triggers _jailing_.
This is wrong, also we don't have the negligible threshold parameter anymore. I believe you might be referring to what is now called `withholding threshold`?

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +- on breaking the _negligible threshold_: jailing and withholding of all staking rewards and newton inflation rewards for the epoch. The _offending validator_ is jailed for a number of epochs determi
same here, this is for the inactivity threshold, not the negligible

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +- on committing an _offence_ when on _probation_: slashing and permanent jailing. The _offending validator_ is slashed according to the protocol's _initial slashing rate_ configured value, validator'
permanent jailing happens only if slashed 100%, while offence while on probation doesn't imply 100% slash.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +On *permanent* jailing the validator enters a `jailboundForInactivity` state and is *permanently* jailed. It becomes [jailbound](/glossary/#jailbound) and cannot get out of jail. Permanent jailing is
same here

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +Slashing penalties for an _offending validator_ are computed by the protocol based on the offending validator's _aggregated inactivity score_, its _offence_ history, if it is on _probation_, and the
```suggestion
Slashing penalties for an _offending validator_ are computed by the protocol based on the offending validator's _aggregated inactivity score_, its _offence_ history, if it is on _probation_, and the total number of offences committed in the current by other committee members, i.e. a _collusion degree_. For the omission fault parameters see [slashing protocol configuration](/concepts/ofd/#slashing-protocol-configuration) beneath.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +Slashing is applied as part of the state finalization function. As the last block of an epoch is finalized, OFD will apply slashing for proven _omission faults_ to withhold ATN staking rewards and NT
```suggestion
Slashing is applied as part of the state finalization function. As the last block of an epoch is finalized, OFD will apply penalties for proven _omission faults_ to withhold ATN staking rewards and NTN inflation rewards, slash validator stake per Autonity's [Penalty-Absorbing Stake (PAS)](/glossary/#penalty-absorbing-stake-pas) model, and applying validator jailing if detected committing an _omission fault_ while on _probation_.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +| _past performance weight_ | a factor that determines how much weight is given to past performance of the validator in the preceding epoch. The factor is subtracted from the validator's performance
```suggestion
| _past performance weight_ | a factor that determines how much weight is given to past performance of the validator in the preceding epoch| `1000` (10%) |
```

No need for this implementation detail

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +| _initial slashing rate_ | the division precision used as the denominator when computing the slashing amount of a penalty | `25` (0.25%) |
this definition needs to be corrected

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +Slashing will also scale up quadratically with the collusion degree, since it helps to safeguard the liveness of the network.
```suggestion
Slashing will also scale up linearly with the collusion degree, since it helps to safeguard the liveness of the network.
```

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +| Loss of current epoch block proposer rewards | n/a  | n/a | The _block proposer_ does not earn proposer rewards for a block outside the [_delta_ $\Delta$](/concepts/ofd/#delta-delta) if it includes
```suggestion
| Loss of current epoch block proposer rewards | n/a  | n/a | The _block proposer_ does not earn proposer rewards for a block if it includes an [_activity proof_](/concepts/ofd/#activity-proof) that does not contain signatures for $> \frac{2}{3}$ of block quorum voting power. See [Proposer reward calculation](/concepts/ofd/#proposer-reward-calculation) formula.|
```

implementation detail + removing imprecise sentence. If a validator doesn't put in any effort, his part of rewards will simply be distributed among the other proposers. I.e. that sum doesn't get re-injected in the epoch rewards.

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +| Loss of current epoch block proposer rewards | n/a  | n/a | The _block proposer_ does not earn proposer rewards for a block outside the [_delta_ $\Delta$](/concepts/ofd/#delta-delta) if it includes
In the edge case that the total effort of the entire network is 0 (basically impossible) the entire sum of proposer rewards will be redistributed at the next epoch (always following the proposer rewards logic). However it is a so rare edge case I don't think it is even worth it to mention it in the docs. It will just confuse people .

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +:::
I am not sure what this callout tries to communicate, since it mixes up proposer rewards and withheld rewards

2025-04-17 14:52 UTC, lorenzo-dev1 commented on concepts/ofd/index.md
> +| withheld rewards | [`withheldRewardsPool`](/reference/genesis/#config.autonity-object) account | epoch end | ATN staking rewards and NTN inflation rewards earned by the _offending validator_ for th
```suggestion
| withheld rewards | [`withheldRewardsPool`](/reference/genesis/#config.autonity-object) account | epoch end | ATN staking rewards and NTN inflation rewards earned by the _offending validator_ for the epoch are forfeited and are sent to the withheld pool account for community funding. Amount determined by the validator's share of the committee's [voting power](/glossary/#voting-power), the number of transactions processed during the epoch, the emission of the [Newton inflation mechanism](/concepts/protocol-assets/newton/#total-supply-and-newton-inflation). |
```

2025-04-22 08:29 UTC, cmjc commented on reference/api/web3/index.md
> +Recommended usage is to make JSON-RPC calls to Autonity Contract Interfaces using `eth_call` from the Web3 [eth namespace](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-eth) wherever po
ok

2025-04-23 10:20 UTC, cmjc commented on concepts/ofd/index.md
> +Rewards are paid to block proposers for including as many signatures in the $ActivityProof$ as possible. The _block proposer_ reward is a fraction of transaction fees earned by protocol in the epoch.
I think that's pretty good @lorenzo-dev1 . I added a missing fullstop; committing suggestion. 👍

2025-04-23 11:53 UTC, cmjc commented on concepts/oracle-server/index.md
> +
@Jason-Zhangxin-Chen - has the edit addressed the comment, please?

2025-04-23 11:53 UTC, jay-cousins commented on concepts/oafd/index.md
> +#### Price report
@Jason-Zhangxin-Chen - has the edit addressed the comment, please?

2025-04-23 13:30 UTC, cmjc commented on oracle/run-oracle/index.md
> +2. Build the plugin. If building oracle server from binary, then customise the plugin before running `make autoracle`. Alternatively, build the plugin individually a describ ed in [/plugins/README, B
Right, this is the case in v0.2.3. Edited to simplify and reword in commit 5d40885fdf40c390de89614d392aa4c020100d66

---

This section removed in its entirety:

```
Default configuration is specified in the crypto plugins' source golang files in a `defaultConfig` structure. To change the default configuration that structure needs to be edited before building the plugin.

::: {.callout-important title="Only the DEX `crypto_uniswap` plugin requires customisation of the default configuration" collapse="true"}
The validator operator must re-configure the `crypto_uniswap` connector to provide data to their own validator node.

This is because the `crypto_uniswap`plugin [`defaultConfig`](https://github.com/autonity/autonity-oracle/blob/v0.2.3/plugins/crypto_uniswap/crypto_uniswap.go#L26) is set to a testing configuration using an `rpc1-internal` endpoint on the Piccadilly Testnet. If the configured endpoint is not changed, then the plugin will be configured to take data from the rpc1-internal testnet node and not your own validator node state.

It is better practice to retrieve ATN, NTN price data from on-chain using your own hosted validator node rather than testnet infrastructure.
:::

Customise the `crypto_uniswap`plugin:

1. Edit the [`defaultConfig`](https://github.com/autonity/autonity-oracle/blob/v0.2.3/plugins/crypto_uniswap/crypto_uniswap.go#L26) in the source golang file must be edited to change:

    - [`defaultConfig.Endpoint`](https://github.com/autonity/autonity-oracle/blob/v0.2.3/plugins/crypto_uniswap/crypto_uniswap.go#L28): change the `endpoint` to replace the `rpc1-internal` endpoint with the endpoint address of their own connected validator node.
    - [`defaultConfig.Scheme`](https://github.com/autonity/autonity-oracle/blob/v0.2.3/plugins/crypto_uniswap/crypto_uniswap.go#L29): update to the scheme used for the endpoint (http/s or ws/s).

2. Build the plugin. If building oracle server from source, then customise the plugin before running `make autoracle`. Alternatively, build the plugin individually as described in [/plugins/README, Build it](https://github.com/autonity/autonity-oracle/blob/v0.2.3/plugins/README.md#build-it). In the `autonity-oracle` directory run:
   
     ```yaml
     go build -o ./build/bin/plugins/crypto_uniswap ./plugins/crypto_uniswap/crypto_uniswap.go
     ```

The other crypto CEX plugins require no customisation. No additional action is required. These can be run run out the box as-is:

- `crypto_kraken`
- `crypto_coingecko`
- `crypto_coinbase`

```

2025-04-28 11:44 UTC, cmjc commented on concepts/oracle-server/index.md
> +
Marking as resolved @Jason-Zhangxin-Chen - please reopen if you think required.

2025-04-28 11:44 UTC, cmjc commented on concepts/oafd/index.md
> +#### Price report
Marking as resolved @Jason-Zhangxin-Chen - please reopen if you think required.

2025-04-28 12:05 UTC, jay-cousins commented on glossary/index.md
> +During the vote period [Autonity oracles](/glossary/#autonity-oracle-server-aos) collect price data from data providers and submit price data reports on-chain for [currency pair](/glossary/#currency-
Fixed in commit 0655a73ec127c16d42c275f38bb54a172831f7bb

2025-04-28 12:50 UTC, cmjc commented on reference/protocol/index.md
> +| `initialSlashingRate` | The division precision used as the denominator when computing the slashing amount of a penalty | Set by default to `25` (0.25%) | See [`setInitialSlashingRate()`](/reference
Reworded and corrected to:

>The initial slashing rate used with the offence count and collusion degree when computing the slashing amount of a penalty

2025-04-28 12:50 UTC, cmjc commented on reference/protocol/index.md
> +| `initialSlashingRate` | The division precision used as the denominator when computing the slashing amount of a penalty | Set by default to `25` (0.25%) | See [`setInitialSlashingRate()`](/reference
Commit b7bdba65650408da2824ea610545f55dc2a4150b

2025-04-28 12:57 UTC, cmjc commented on reference/genesis/index.md
> +| `abi` | The abi of an upgraded Autonity Oracle Contract to be deployed at genesis. By default the Autonity Oracle Contract in the Autonity Go Client release is deployed. Only specify if overriding
Correct. Removed in commit 182ab66bc29796e983747c88eddedaa253f17853

2025-04-28 13:01 UTC, cmjc commented on concepts/ofd/index.md
> +| _initial slashing rate_ | the division precision used as the denominator when computing the slashing amount of a penalty | `25` (0.25%) |
Corrected as done for comment https://github.com/autonity/docs.autonity.org/pull/259#discussion_r2063589147.  Commit 200393b55d70094556206c67eb6661a40614de87

2025-04-28 13:11 UTC, cmjc commented on concepts/ofd/index.md
> +:::
Re-reading it, completely agree.

Deleted in commit f1aab07ed219300f67fcbadd84053bde435f6ebc

2025-04-28 13:42 UTC, cmjc commented on reference/api/web3/index.md
> +:::
I've edited in commit 425eca23cad919c7c5c6f968f986976c2bdd3a48, but I'm not sure if this addresses the issue. Please re-review.

2025-04-28 13:51 UTC, cmjc commented on concepts/staking/index.md
> +Newton inflation rewards are distributed to [participating](/glossary/#participation-rate) stake at the end of each epoch by the Newton [inflation mechanism](/glossary/#inflation-mechanism). The newt
Correction made in commit 51fa4d128a6d3e2c728e6925ae18b0dbe4201e77

2025-04-28 13:54 UTC, cmjc commented on concepts/staking/index.md
> +The bonding request is tracked in memory for application at the end of the epoch in which $T$ was processed. At this point, the validator's bonded stake is increased, and Liquid Newton is issued to A
Yes, that does read better. Reworded to this:

```
::: {.callout-note title="Note" collapse="false"}
Alice submits a [`bond()`](/reference/api/aut/#bond) tx that is processed and included in a block at time $T$, where a `BondingRequest` object for the necessary voting power change is also created. Newton is burnt at $T$. Actual bonding is then executed at $T$ + remainder of the epoch. Liquid Newton issuance is delayed and not tradable while bonding is pending.

The bonding request is tracked in memory for application at the end of the epoch in which $T$ was processed. At this point, the validator's bonded stake is increased, and Liquid Newton is issued to Alice in the validator’s Liquid Newton ERC20 contract.
:::
```

Commit: e96b3207fcdc02eddc5268d4883ae4a2fe6fe986

2025-04-28 14:14 UTC, cmjc commented on concepts/validator/index.md
> +    6.b. Permanent jailing: `jailbound` or `jailboundForInactivity` state. In this state the validator is *permanently* jailed and becomes [jailbound](/glossary/#jailbound). Permanent jailing is only
The balance is having detail here on the Validator page that repeats text on the OFD page. IThe simple edit here is to make 'inactivity offence' plural:

- from:

  >or for committing an inactivity offence while on probation by [OFD](/concepts/ofd/).

- to:

>or for committing multiple inactivity offences while on probation by [OFD](/concepts/ofd/).


But is that too naive?  Please see commit e446617587b2908a65485e816f4a64f831fca75b

2025-04-28 14:18 UTC, cmjc commented on concepts/validator/index.md
> +  - Newton [inflation rewards](/glossary/#inflation-rewards) accrue to all bonded stake irrespective of whether it is active in the current consensus committee or not. [Delegated](/glossary/#delegate
Yes, commit 1e94888e17acfb1eefd1538256621c65bee0884d.

(Also, the following paragraph on ATN staking rewards is no longer relevant to the explanatory callout and has been removed in this commit.)

2025-04-28 14:21 UTC, jay-cousins commented on concepts/validator/index.md
> +  - This is in contrast to [staking rewards](/glossary/#staking-rewards) where staking rewards are only earned when the validator bonded to is active in the current consensus committee. The stakers w
Yes, per comment in https://github.com/autonity/docs.autonity.org/pull/259#discussion_r2063765813, deleted this bullet point.

2025-04-28 14:33 UTC, cmjc commented on concepts/validator/index.md
> +- On permanent jailing the validator enters a `jailbound` or `jailboundForInactivity` state and is *permanently* jailed. It becomes [jailbound](/glossary/#jailbound) and cannot get out of jail. Perma
Edited - change made as described in previous comment https://github.com/autonity/docs.autonity.org/pull/259#discussion_r2063755996

2025-04-28 15:21 UTC, cmjc commented on concepts/ofd/index.md
> +OFD functions, therefore, by submitting, verifying, and processing activity proofs for omission faults captured over a rolling block window by epoch.
'a validator'.  Corrected in commit d3418f44ded34a933f3a7dff40f12b8e087ee6cc.

2025-04-28 15:22 UTC, cmjc commented on concepts/ofd/index.md
> +- withholding of OFD proposer fee reward incentives proportionally to the offline % of in the epoch, measured by the % of blocks the validator was offline for in the epoch
Gotcha - there has been a conflation of proposer and ATN staking rewards withholding when it is only ATN staking rewards. Corrected in commit d3418f44ded34a933f3a7dff40f12b8e087ee6cc.

2025-04-28 15:22 UTC, cmjc commented on concepts/ofd/index.md
> +The Autonity community is also a _beneficiary_ of OFD processing. Slashed stake token, withheld proposer fee rewards, and withheld Newton inflation rewards will be used for community funds.
Per https://github.com/autonity/docs.autonity.org/pull/259#discussion_r2063912019, corrected in commit d3418f44ded34a933f3a7dff40f12b8e087ee6cc.

2025-04-28 15:54 UTC, cmjc commented on concepts/ofd/index.md
> +$\Delta$ is the number of blocks committee members wait for before generating an activity proof. I.e. activity proof for block $x$ is going to be computed at block $x+\Delta$. The $\Delta$ allows for
Clarified in commit 8e52388fb1866300309c6619bc53c379f442c16c.

2025-04-28 16:27 UTC, cmjc commented on concepts/ofd/index.md
> +The $\Delta$ allows for two temporal factors, epoch periods and the network's semi-synchronous nature. Firstly, it allows for a fair start of an epoch and prevents the _block proposer_ looking for in
Following discussion with @lorenzo-dev1 , edited in commits 8e52388fb1866300309c6619bc53c379f442c16c and ec44b38195b129d446878533afc079a3f05d32c9

2025-04-29 09:02 UTC, cmjc commented on concepts/ofd/index.md
> +The _inactivity scores_ for the current and past epoch are aggregated to computes an _aggregated inactivity score_. Penalties are applied only if a committee member's _aggregated inactivity score_ br
Reworded the paragraph for this and to remove redundancy with the following sub-section on probation:

>The _inactivity scores_ for the current and past epoch are combined to compute an _aggregated inactivity score_. Penalties are applied only if a committee member's _aggregated inactivity score_ breaks the _inactivity threshold_ during an epoch. Penalties are then computed based on the validator's historical _omission fault_ history. A validator's history of _omission faults_ is maintained by an _offence_ counter. The counter increments by `1` for each _omission fault_ committed, but is reset to `0` if a validator's _probation period_ expires without the validator committing an _offence_ while on [_probation_](/concepts/ofd/#probation). The validator's _aggregated inactivity score_ and _offence_ count are used as weighting factors when computing omission penalties.

2025-04-29 10:31 UTC, cmjc commented on concepts/ofd/index.md
> +The _inactivity scores_ for the current and past epoch are aggregated to computes an _aggregated inactivity score_. Penalties are applied only if a committee member's _aggregated inactivity score_ br
Corrected in commit f0ad427b9e8df012a3adf4bb5c0e7acf0d47bf63.

2025-04-29 10:31 UTC, cmjc commented on concepts/ofd/index.md
> +- The _negligible threshold_ sets a floor which if broken triggers _jailing_.
Correct. Revised after conversation with @ScottRMalley , commit f0ad427b9e8df012a3adf4bb5c0e7acf0d47bf63.

2025-04-29 10:32 UTC, cmjc commented on concepts/ofd/index.md
> +- on breaking the _negligible threshold_: jailing and withholding of all staking rewards and newton inflation rewards for the epoch. The _offending validator_ is jailed for a number of epochs determi
Corrected in commit f0ad427b9e8df012a3adf4bb5c0e7acf0d47bf63 after discussion with @ScottRMalley

2025-04-29 10:32 UTC, cmjc commented on concepts/ofd/index.md
> +- on committing an _offence_ when on _probation_: slashing and permanent jailing. The _offending validator_ is slashed according to the protocol's _initial slashing rate_ configured value, validator'
Fixed in commit f0ad427b9e8df012a3adf4bb5c0e7acf0d47bf63.

2025-04-29 10:32 UTC, cmjc commented on concepts/ofd/index.md
> +On *permanent* jailing the validator enters a `jailboundForInactivity` state and is *permanently* jailed. It becomes [jailbound](/glossary/#jailbound) and cannot get out of jail. Permanent jailing is
Corrected in commit f0ad427b9e8df012a3adf4bb5c0e7acf0d47bf63.

2025-04-30 17:13 UTC, lorenzo-dev1 submitted a review, later dismissed
LGTM

2025-05-21 14:32 UTC, aiman requested changes
Overall great with many welcome changes! High level feedback is that it would be great to correct at least the whitespace errors that were introduced in this PR, ala `git diff --check master..` for example. There is also a wider discussion point on consistent capitalization as referenced in several comments.

2025-05-21 14:32 UTC, aiman commented on concepts/client/index.md
> +- _Autonity Oracle Contract_, the oracle protocol contract providing operations for: computing median price data, managing the currency-pair symbols for which price data is provided by the Autonity o
Please review capitalization of protocol contract names and/or notable protocol concepts.

2025-05-21 14:32 UTC, aiman commented on concepts/oafd/index.md
> +- The secondary consumer of the data is use cases deployed on the Autonity L1.
Looks like unnecessary use of lists, can be flattened:

```
Autonity provides consensus-computed median price data for a designated set of [_currency pair_](/glossary/#currency-pair) (AKA _symbols_) as an L1 platform feature for primary and secondary consumer use cases.

The primary consumer of the data is the [Auton Stabilisation Mechanism (ASM)](/concepts/asm/):

  - FX price data: for the _currency pairs_ used as the FX currency basket in the [ACU](/concepts/asm/#acu) index, and,
  - Autonity NTN and ATN [protocol assets](/concepts/protocol-assets/) price data: for ATN borrowing against NTN collateral by the [CDP](/concepts/asm/#stabilization) mechanism.

The secondary consumer of the data is use cases deployed on the Autonity L1.
```

Or perhaps flattened even further, because this is only background information and does not not need to take up so much vertical space (ie. prominence) relative to the subject of the page. For example:

```suggestion
Autonity provides consensus-computed median price data for a designated set of [_currency pair_](/glossary/#currency-pair) (AKA _symbols_) as an L1 platform feature for primary and secondary consumer use cases. The primary consumer of the data is the [Auton Stabilisation Mechanism (ASM)](/concepts/asm/), which uses the _currency pairs_ as the FX currency basket in the [ACU](/concepts/asm/#acu) index. Also, Autonity NTN and ATN [protocol assets](/concepts/protocol-assets/) price data are used for ATN borrowing against NTN collateral by its [CDP](/concepts/asm/#stabilization) mechanism. The secondary consumer of the data is the use cases deployed on the Autonity L1.
```

2025-05-21 14:32 UTC, aiman commented on concepts/architecture/index.md
Extensive and well-written changes here!

2025-05-21 14:32 UTC, aiman commented on concepts/oafd/index.md
> +::: {.callout-caution title="What if that _last submitted price_ was an _outlier_?" collapse="false"}
Good idea to use a callout!

2025-05-21 14:32 UTC, aiman commented on concepts/oafd/index.md
> +
Not sure about the use of :pie:... Was the intention to show a slice? Note that this emoji represents a _whole pie_ so it cannot be relied upon to show a slice. In fact, on Github it renders as a slice but in Quarto it renders a whole pie.

2025-05-21 14:32 UTC, aiman commented on concepts/oracle-server/index.md
> +- _Autonity Oracle Contract_, the oracle protocol contract logic deployed to the ledger by AGC. The Oracle Contract manages the computation of median price data for currency pair price reports submit
Further to my comment elsewhere, I wonder whether protocol components should be capitalized, such as Oracle Accountability Fault Detection, and whether this is being applied consistently or not.

2025-05-21 14:32 UTC, aiman commented on concepts/protocol-assets/newton/index.md
> +The total supply of Newton will be set to 100 million NTNs. 40% of the total supply is set aside as an "inflation reserve" for [inflation rewards](/glossary/#inflation-rewards) released into circulat
newton -> Newton

?

2025-05-21 14:32 UTC, aiman commented on concepts/staking/index.md
> +Newton inflation rewards are distributed to [participating](/glossary/#participation-rate) stake active in the consensus committee at the end of each epoch by the Newton [inflation mechanism](/glossa
newton or Newton?

2025-05-21 14:32 UTC, aiman commented on concepts/staking/index.md
> +Newton [inflation rewards](/glossary/#inflation-rewards) are minted and distributed to stakers at the end of each epoch by the Newton [inflation mechanism](/glossary/#inflation-mechanism). On emissio
> Newton inflation rewards are a distribution of newly minted newton by the Newton inflation mechanism...

Not sure about capitalization for newton or Newton.

As for inflation mechanism vs Inflation Mechanism, I would suggest the former is a generic description of a mechanism, the latter is a reference to the Autonity mechanism specifically.

2025-05-21 14:32 UTC, aiman commented on concepts/staking/index.md
The changes from `code formatting` to $MathJax markup$ for variables here and in other pages is a good idea, it looks more appropriate and consistent with other text blocks that make use of equations more heavily.

2025-05-21 14:32 UTC, aiman commented on concepts/staking/index.md
> +- [Oracle accountability fault detection protocol (OAFD)](/concepts/oafd/) for failing to submit accurate price reports to the oracle protocol on-chain.
capitalization issue?

2025-05-21 14:32 UTC, aiman commented on concepts/staking/index.md
> +| [Oracle accountability fault detection protocol (OAFD)](/concepts/oafd/) | [outlier penalties](/concepts/oafd/#outlier-penalties)|
capitalization issue?

2025-05-21 14:32 UTC, aiman commented on concepts/validator/index.md
> +| [Oracle accountability fault detection protocol (OAFD)](/concepts/oafd/) | [outlier penalties](/concepts/oafd/#outlier-penalties)|
In this doc page, Proof of Stake is capitalized. Also Penalty-Absorbing Stake (PAS). So would it not be appropriate also to do same for AFD, OFD, OAFD?

I've already left a few comments earlier in the review on the topic, so probably not worth repeating them on every occurrence. So note there may be more occurrences in case they need to be reviewed.

2025-05-21 14:32 UTC, aiman commented on issues/index.md
> +As part of addressing AGC issue [Revise the `aut` JSON-RPC Namespace #1034](), the `acnPeers` RPC call was moved from the `admin` to `aut` namespace.
```
As part of addressing AGC issue [Revise the `aut` JSON-RPC Namespace #1034](), the `acnPeers` RPC call was moved from the `admin` to `aut` namespace.
```

the link to 1034 is missing

2025-05-21 14:32 UTC, aiman commented on node-operators/install-aut/index.md
> +* `TCP 20203` for node p2p (DEVp2p) communication for *consensus gossiping*.
good idea to move this here and make it more prominent

2025-05-21 14:32 UTC, aiman commented on oracle/run-oracle/index.md
> +| Option | Description |
Indeed, a table makes the options much easier to review

2025-05-21 14:32 UTC, aiman commented on oracle/run-oracle/index.md
> +| Name | Datatype | Mandatory? | Description |
In this table, consider using checkbox ✓ Unicode character for "required" and omitting the checkbox to mean "optional".

2025-05-21 14:32 UTC, aiman commented on reference/api/aut/index.md
> +Returns the total amount of Auton staking rewards distributed since genesis minus treasury fee.
Elsewhere in the docs, in this PR as well, there is usage of auton in lower case but it seems that uppercase is more appropriate and should be used more consistently.

2025-05-21 14:32 UTC, aiman commented on reference/api/aut/index.md
> +    }
There is no point to including more than a few validators in this output. It takes up a lot of space in the page and serves no purpose! I would suggest editing by hand to trim to 1-3 items or else making use of ellipses...

2025-05-21 14:32 UTC, aiman commented on reference/api/aut/index.md
> +  "committee": [
As per previous comment, there is no point including 60+ validators in this output as it takes up space for no benefit AFAIK.

2025-05-21 14:32 UTC, aiman commented on reference/api/aut/index.md
> +gReleased 2
There is an erroneous newline here:

```suggestion
aut contract call --abi ../scripts/abi/v1.0.2-alpha/Autonity.abi  --address 0xBd770416a3345F91E4B34576cb804a576fa48EB1  isUnbondingReleased 2
```

2025-05-21 14:32 UTC, aiman commented on reference/api/liquid-newton/index.md
> +Queries the contract and returns the total ATN rewards owed to a given account.
Not sure what is served by saying "queries the contract":

```suggestion
Returns the total ATN rewards owed to a given account.
```

2025-05-21 14:32 UTC, aiman commented on reference/api/oracle/index.md
> +A data consumer can convert the L2 aggregation value to decimal precision for their use case by applying the number of decimal places as the precision.
incorrect usage of "L2" here

2025-05-21 14:32 UTC, aiman commented on reference/api/web3/aut/index.md
> +100  1109  100  1044  100    65   2691    167 --:--:-- --:--:-- --:--:--  2865
- add option `-s` to curl command
- omit extraneous output from `curl`

```suggestion
curl -s -X GET $RPC_URL --header 'Content-Type: application/json' --data '{"method":"aut_acnPeers", "params":[], "jsonrpc":"2.0", "id":1}' | jq .
```

2025-05-21 14:32 UTC, aiman commented on reference/api/web3/index.md
> +::: {.callout-note title="Configuring access to the JSON-RPC APIs" collapse="true"}
useful addition this

2025-05-21 14:32 UTC, aiman commented on networks/testnet-bakerloo/index.md
Why not just delete this file as it's unreachable from the site navigation? I think this is preferable to having out of date content in the repo. It can always be found in git history.

2025-05-21 14:34 UTC, aiman commented on concepts/architecture/index.md
> +- Calculate penalties based on parameters set in the [protocol configuration](/concepts/ofd/#protocol-configuration) and dynamic factors specific to the epoch circumstances. See [slashing amount calc
> - Calculate penalties...

This is an unnecessary bullet point (solo item does not necessitate a list).

2025-05-21 14:35 UTC, aiman commented
Also reminder @cmjc to check for hidden conversations

2025-05-21 15:10 UTC, jay-cousins commented on networks/testnet-bakerloo/index.md
That's true. Removed in commit 02ad8e34195d4d629cce7872a6f9a32676323a96.

2025-05-21 15:16 UTC, cmjc commented on concepts/architecture/index.md
> +- Calculate penalties based on parameters set in the [protocol configuration](/concepts/ofd/#protocol-configuration) and dynamic factors specific to the epoch circumstances. See [slashing amount calc
I'm trying to keep consistent formatting style throughout the sections, hence a solo point, but removed in commit c4ccb4dccb62cee53501edb2817c2d888fdb686b and edited to:

>... The contract calculates penalties based on parameters set in the [protocol configuration](/concepts/oafd/#protocol-configuration) and dynamic factors specific to the epoch circumstances. See [slashing amount calculation](/concepts/ofd/#slashing-amount-calculation).

2025-05-21 15:20 UTC, cmjc commented on reference/api/oracle/index.md
> +A data consumer can convert the L2 aggregation value to decimal precision for their use case by applying the number of decimal places as the precision.
That should be "on-chain". Corrected in commit 258c0b936f093f0f38f0817dea0ce682829b588c.

2025-05-21 15:23 UTC, cmjc commented on concepts/oafd/index.md
> +
Yes. As you say a pie or slice, platform dependent. I will remove the :pie:.  Removed in commit 00723630eff2a60ac3c649024d6568d65fe16247.

2025-05-21 15:36 UTC, cmjc commented on concepts/protocol-assets/newton/index.md
> +The total supply of Newton will be set to 100 million NTNs. 40% of the total supply is set aside as an "inflation reserve" for [inflation rewards](/glossary/#inflation-rewards) released into circulat
That should be Newton.

The convention used for Newton (and Auton) capitalization is:

- Capitalise when speaking specifically about Newton the currency as a proper noun, or when used at the beginning of the sentence.
- Lowercase when referring to in general. 

So above should be newton not Newton. If it was capitalised because of total supply, that was wrong as to speak of the supply is general; i.e. rather than using Newton as a proper noun. 

Corrected in commit 6589308254192e358f6889775e1079d5f1b65ada.

2025-05-21 15:40 UTC, cmjc commented on concepts/staking/index.md
> +Newton inflation rewards are distributed to [participating](/glossary/#participation-rate) stake active in the consensus committee at the end of each epoch by the Newton [inflation mechanism](/glossa
This is capitalized as the Newton inflation mechanism is a specific thing. In the sense the "Newton inflation mechanism" is a proper noun, whereas "inflation mechanism" is the class of inflation mechanisms. Hence, "Newton" not "newton" here.

2025-05-21 15:45 UTC, cmjc commented on concepts/staking/index.md
> +Newton [inflation rewards](/glossary/#inflation-rewards) are minted and distributed to stakers at the end of each epoch by the Newton [inflation mechanism](/glossary/#inflation-mechanism). On emissio
The first 2 paragraphs follow the comments made earlier - see https://github.com/autonity/docs.autonity.org/pull/259#discussion_r2100604028 and https://github.com/autonity/docs.autonity.org/pull/259#discussion_r2100613432.

Same for the first 2 instances in paragraph 3, but the last instance in paragraph 3 is wrong - that should be "newton" not "Newton".

Corrected in commit c0e4306d0a03361c6b54596116a8f96c1dbb2994.

2025-05-21 16:20 UTC, cmjc commented on concepts/oracle-server/index.md
> +- _Autonity Oracle Contract_, the oracle protocol contract logic deployed to the ledger by AGC. The Oracle Contract manages the computation of median price data for currency pair price reports submit
This is inconsistent:

1. Protocol contracts: are capitalised on the Architecture page e.g. "Oracle Protocol Contract" . The thinking was references on this page are to the thing itself, the propoer noun, so capitalisation is correct. Elsewhere in the docs, it becomes inconsistent. E.g. it is "Oracle contract" in the OAFD page.

2. Components: are capitalised on the Architecture page with an acronym, e.g. Autonity Go Client (AGC) Autonity Oracle Server (AOS). When referred to then if the full name is used it is capitalised (Autonity Go Client) or the acronym (AGC) is used. It is not capitalised if the full name is not used - e.g. oracle server, or main client.

3. Accountability protocols. This is inconsistent. It's generally referred to in lower case, the acronym in upper case. e.g. "Autonity accountability fault detection protocol (AFD)" or "accountability fault detection protocol (AFD)" or "Accountability Fault Detection protocol (AFD)"

4. Page headings. Editorial decision was to use capitalisation of the first word only unless a proper noun. Hence Autonity Go Client (AGC), Auton Stabilization Mechanism (ASM). This is inconsistent as according to this the accountability  protocol page headings should be capitalised - e.g. "Accountability Fault Detection (AFD)" not "Accountability fault detection (AFD)".

5. Page section headings. Editorial decision was to use capitalisation of the first word only. There are some instances on the Architecture (Consensus Layer) and accountability pages (e.g. Accountability Fault Detection protocol) to do 

@aiman suggest to remedy:

1. Protocol contracts. I would leave the Architecture page as-is, but check it. Elsewhere, if used as a proper noun it is capitalised, otherwise it is made lower case. E.g. elsewhere instances of "Oracle contract" becomes "oracle contract". This will mainly impact the Concepts and Interfaces pages.
2. Components. I think this is correct as-is.
3. Accountability protocols. Same proper noun convention. First time it is introduced and described, it's a proper noun and capitalised (e.g. Accountability Fault Detection protocol (AFD)). Thereafter it is "accountability fault detection protocol" or "AFD" or "AFD protocol"
4. Page headings. Changed to use capitals for proper nouns. This only impacts the accountability protocol concept pages - AFD, OFD, OAFD. These should be capitalised (e.g. Accountability Fault Detection protocol (AFD)). And, on these pages, capitalisation used per (3) above.
5. Page section headings. Changed so they consistently have only the first word capitalised

Dis/agree?

2025-05-21 16:20 UTC, cmjc commented on concepts/client/index.md
> +- _Autonity Oracle Contract_, the oracle protocol contract providing operations for: computing median price data, managing the currency-pair symbols for which price data is provided by the Autonity o
Please see proposal in https://github.com/autonity/docs.autonity.org/pull/259#discussion_r2100705503

2025-05-22 09:28 UTC, cmjc commented on issues/index.md
> +As part of addressing AGC issue [Revise the `aut` JSON-RPC Namespace #1034](), the `acnPeers` RPC call was moved from the `admin` to `aut` namespace.
👁️‍🗨️ well spotted! That issue <https://github.com/autonity/autonity/issues/1034> is closed and the PR making the fix <https://github.com/autonity/autonity/issues/1034> is now merged in.

So I'm removing the known issue on this page, and the note referring to it in the `aut` namespace page - `/reference/api/web3/aut/#aut_acnpeers`.

Commit 8975a03488ad75d91617f2a858a55776c93a34be.

2025-05-22 09:31 UTC, cmjc commented on oracle/run-oracle/index.md
> +| Option | Description |
Yup.

2025-05-22 09:51 UTC, cmjc commented on oracle/run-oracle/index.md
> +| Name | Datatype | Mandatory? | Description |
There's an interesting GitHub gist [Checkbox Tables in Markdown](https://gist.github.com/TheMatt2/1360af52468714370c753cfa2fe50783).

I've used the HTML entity approach - &#x2714;

Commit 62a81af5ffee2cc164232ff9f604eac6de3b035e

2025-05-22 09:59 UTC, jay-cousins commented on reference/api/aut/index.md
> +    }
Agree. Edited down in commit cc12151c0bc12a8728925f8dab97a84859acb52d.

2025-05-22 10:03 UTC, cmjc commented on reference/api/aut/index.md
> +  "committee": [
Agree. Edited down in commit caa0b402c48bf030176c42f1bbface1534207b3e.

2025-05-22 10:24 UTC, aiman commented on concepts/oracle-server/index.md
> +- _Autonity Oracle Contract_, the oracle protocol contract logic deployed to the ledger by AGC. The Oracle Contract manages the computation of median price data for currency pair price reports submit
To address 1-5 in one go: I would prefer to capitalize all proper nouns, regardless of context and location. Whether this is a page heading or a section heading should not affect proper nouns. Also, whether this is on the Architecture page or not should not make a difference.

2025-05-22 11:29 UTC, jay-cousins commented on concepts/oracle-server/index.md
> +- _Autonity Oracle Contract_, the oracle protocol contract logic deployed to the ledger by AGC. The Oracle Contract manages the computation of median price data for currency pair price reports submit
OK, will do.

2025-05-22 15:01 UTC, aiman commented on concepts/oracle-server/index.md
> +- _Autonity Oracle Contract_, the oracle protocol contract logic deployed to the ledger by AGC. The Oracle Contract manages the computation of median price data for currency pair price reports submit
Hopefully it's just a global search-and-replace task, let me know if I can help with some `sed` commands.

2025-05-22 15:27 UTC, cmjc commented on concepts/oracle-server/index.md
> +- _Autonity Oracle Contract_, the oracle protocol contract logic deployed to the ledger by AGC. The Oracle Contract manages the computation of median price data for currency pair price reports submit
This has been done throughout the Concepts section in commit 4dc0780e19c351728dc824ad20187847234b1f2b.

2025-05-22 15:28 UTC, cmjc commented on concepts/client/index.md
> +- _Autonity Oracle Contract_, the oracle protocol contract providing operations for: computing median price data, managing the currency-pair symbols for which price data is provided by the Autonity o
@aiman - capitalisation reviewed and made consistent throughout Concepts section as agreed in your coment https://github.com/autonity/docs.autonity.org/pull/259#discussion_r2102212199.  Commit 4dc0780e19c351728dc824ad20187847234b1f2b.

2025-05-22 15:30 UTC, cmjc commented on concepts/protocol-assets/newton/index.md
> +The total supply of Newton will be set to 100 million NTNs. 40% of the total supply is set aside as an "inflation reserve" for [inflation rewards](/glossary/#inflation-rewards) released into circulat
Also, the entire Concepts section was checked and edits to consistently use capitalisation for Newton, Liquid Newton made. Commit 4dc0780e19c351728dc824ad20187847234b1f2b.

2025-05-22 15:30 UTC, jay-cousins commented on concepts/staking/index.md
> +- [Oracle accountability fault detection protocol (OAFD)](/concepts/oafd/) for failing to submit accurate price reports to the oracle protocol on-chain.
@aiman - capitalisation reviewed and made consistent throughout Concepts section as agreed in your comnent https://github.com/autonity/docs.autonity.org/pull/259#discussion_r2102212199.  Commit 4dc0780e19c351728dc824ad20187847234b1f2b.

2025-05-22 15:31 UTC, cmjc commented on concepts/staking/index.md
> +| [Oracle accountability fault detection protocol (OAFD)](/concepts/oafd/) | [outlier penalties](/concepts/oafd/#outlier-penalties)|
Fixed.  Consistently capitalised as discussed in comment https://github.com/autonity/docs.autonity.org/pull/259#discussion_r2102212199.  Commit 4dc0780e19c351728dc824ad20187847234b1f2b.

2025-05-22 15:32 UTC, jay-cousins commented on concepts/validator/index.md
> +| [Oracle accountability fault detection protocol (OAFD)](/concepts/oafd/) | [outlier penalties](/concepts/oafd/#outlier-penalties)|
Yup. All pages in the Concepts section checked and now consistently capitalized throughout Concepts section as agreed in comment https://github.com/autonity/docs.autonity.org/pull/259#discussion_r2102212199.  Commit 4dc0780e19c351728dc824ad20187847234b1f2b.

2025-05-22 15:34 UTC, cmjc commented on reference/api/aut/index.md
> +Returns the total amount of Auton staking rewards distributed since genesis minus treasury fee.
This is fixed in the Concepts section (not many changes).  Commit 4dc0780e19c351728dc824ad20187847234b1f2b.

2025-05-22 15:54 UTC, cmjc commented on concepts/oracle-server/index.md
> +- _Autonity Oracle Contract_, the oracle protocol contract logic deployed to the ledger by AGC. The Oracle Contract manages the computation of median price data for currency pair price reports submit
I'm really wary of global search and replace, tbh.  But you're right.

`find . -type f -name "*.md" -exec sed -n '/fault detection/p' {} +` found several missed ones for the accountability protocols, for example.  Further commit(s) to follow.

2025-05-22 16:48 UTC, cmjc commented on concepts/oracle-server/index.md
> +- _Autonity Oracle Contract_, the oracle protocol contract logic deployed to the ledger by AGC. The Oracle Contract manages the computation of median price data for currency pair price reports submit
Further fixes in commits dfb84273d3582fd3d2a26342642bbe14a9882b99 and 2cc1eb9d5214030bd5af2836e3f9d258420a3ca0.

2025-05-22 16:48 UTC, jay-cousins commented on reference/api/aut/index.md
> +Returns the total amount of Auton staking rewards distributed since genesis minus treasury fee.
Further fixes in commits dfb84273d3582fd3d2a26342642bbe14a9882b99 and 2cc1eb9d5214030bd5af2836e3f9d258420a3ca0.

2025-05-22 16:49 UTC, jay-cousins commented on concepts/validator/index.md
> +| [Oracle accountability fault detection protocol (OAFD)](/concepts/oafd/) | [outlier penalties](/concepts/oafd/#outlier-penalties)|
Further fixes in commits dfb84273d3582fd3d2a26342642bbe14a9882b99 and 2cc1eb9d5214030bd5af2836e3f9d258420a3ca0.

2025-05-22 16:49 UTC, cmjc commented on concepts/staking/index.md
> +| [Oracle accountability fault detection protocol (OAFD)](/concepts/oafd/) | [outlier penalties](/concepts/oafd/#outlier-penalties)|
Further fixes in commits dfb84273d3582fd3d2a26342642bbe14a9882b99 and 2cc1eb9d5214030bd5af2836e3f9d258420a3ca0.

2025-05-22 16:49 UTC, jay-cousins commented on concepts/staking/index.md
> +- [Oracle accountability fault detection protocol (OAFD)](/concepts/oafd/) for failing to submit accurate price reports to the oracle protocol on-chain.
Further fixes in commits dfb84273d3582fd3d2a26342642bbe14a9882b99 and 2cc1eb9d5214030bd5af2836e3f9d258420a3ca0.

2025-05-22 16:49 UTC, cmjc commented on concepts/protocol-assets/newton/index.md
> +The total supply of Newton will be set to 100 million NTNs. 40% of the total supply is set aside as an "inflation reserve" for [inflation rewards](/glossary/#inflation-rewards) released into circulat
Further fixes in commits dfb84273d3582fd3d2a26342642bbe14a9882b99 and 2cc1eb9d5214030bd5af2836e3f9d258420a3ca0.

2025-05-22 16:49 UTC, cmjc commented on concepts/oracle-server/index.md
> +- _Autonity Oracle Contract_, the oracle protocol contract logic deployed to the ledger by AGC. The Oracle Contract manages the computation of median price data for currency pair price reports submit
Further fixes in commits dfb84273d3582fd3d2a26342642bbe14a9882b99 and 2cc1eb9d5214030bd5af2836e3f9d258420a3ca0.

2025-05-22 16:56 UTC, jay-cousins commented
@aiman - commits for edits requested and comments made. Checked for Git Hub 'hidden conversations' masking comments. Re-requesting review. 👍

2025-05-22 16:56 UTC, cmjc commented on concepts/client/index.md
> +- _Autonity Oracle Contract_, the oracle protocol contract providing operations for: computing median price data, managing the currency-pair symbols for which price data is provided by the Autonity o
Further fixes in commits dfb84273d3582fd3d2a26342642bbe14a9882b99 and 2cc1eb9d5214030bd5af2836e3f9d258420a3ca0.

2025-05-27 13:19 UTC, merged

2025-05-27 13:19 UTC, aiman commented
Thanks!