Replace autonity rpc with chainlist
autonity/docs.autonity.org pull request #260
Opened 2024-11-22 09:12 UTC by spenot09

In accordance with: https://github.com/autonity/project-execution/issues/379#issue-2632030296

I have replaced all mentions of `https://rpc1.piccadilly.autonity.org/` and `https://rpc1.bakerloo.autonity.org` with references to the relevant Chainlist entries: `https://chainlist.org/?testnets=true&search=piccadilly` and `https://chainlist.org/?testnets=true&search=bakerloo`.

The intention is that as the list of RPC providers may change, this can by reflected on Chainlist, without needing constant Doc updates.

N.B. I know Bakerloo will be retired but just keeping things consistent for now.

2024-11-22 13:00 UTC, cmjc reviewed
I think this is a great idea, though it has the caveat that if chainlist has not been updated it will be out of date.

I'm OK to approve this. @aiman ?

2024-11-22 13:08 UTC, cmjc requested changes
Hyperlink closing braces missing fixes noted.

2024-11-22 13:08 UTC, cmjc commented on networks/testnet-bakerloo/index.md
> +Please select one from [Chainlist](https://chainlist.org/?testnets=true&search=bakerloo. For questions related to rate limits or other usage questions, please speak to the owner of the RPC endpoint d
```suggestion
Please select one from [Chainlist](https://chainlist.org/?testnets=true&search=bakerloo). For questions related to rate limits or other usage questions, please speak to the owner of the RPC endpoint directly.
```

2024-11-22 13:08 UTC, cmjc commented on networks/testnet-piccadilly/index.md
> +Please select one from [Chainlist](https://chainlist.org/?testnets=true&search=piccadilly. For questions related to rate limits or other usage questions, please speak to the owner of the RPC endpoint
```suggestion
Please select one from [Chainlist](https://chainlist.org/?testnets=true&search=piccadilly). For questions related to rate limits or other usage questions, please speak to the owner of the RPC endpoint directly.
```

2024-11-28 10:50 UTC, aiman commented
I think this could be merged into `master` instead of `develop`. So would suggest changing the target branch in the PR settings.

I'm also not sure about readability of the updated language and use of angled brackets in code snippets. We can replace this:

```
curl -X GET <RPC FROM https://chainlist.org/?testnets=true&search=piccadilly> ...
```

with this:

```
curl -X GET $RPC_URL ...
```

And then just write at the top of the page or the start of a section (depending on context):

```
Given an `RPC_URL` from <https://chainlist.org/?testnets=true&search=piccadilly>:
```

2024-12-04 09:02 UTC, spenot09 commented
Thanks for the suggestion @aiman, I've updated it to reflect that

2024-12-05 10:18 UTC, aiman reviewed
Overall looks great!

Just one point I noticed is that `piccadilly` is currently set in some of the URLs:

> https://chainlist.org/?testnets=true&search=piccadilly

Would it be better to just use `autonity` instead?

> https://chainlist.org/?testnets=true&search=autonity

2024-12-05 10:18 UTC, aiman commented on developer/deploy-brownie/index.md
> +Add the testnet you would like to deploy the contract to, given an `RPC_URL` from <https://chainlist.org/?testnets=true&search=piccadilly>::
there's an extra `:` here:

```suggestion
Add the testnet you would like to deploy the contract to, given an `RPC_URL` from <https://chainlist.org/?testnets=true&search=piccadilly>:
```

2024-12-05 10:33 UTC, spenot09 commented
Good suggestion @aiman! I have included the `autonity` search results as suggested. It definitely helps with future proofing further once mainnet is live.

2024-12-05 10:58 UTC, merged