External link fix
autonity/docs.autonity.org pull request #58
Opened 2023-03-29 18:06 UTC by cmjc

Edits to:

- Consistently open external links in new tabs, see #57 
- Fix out of date links to ethereum wiki and geth doc pages found while checking external links

closes #57

2023-04-03 16:21 UTC, aiman approved these changes
I believe this improves the usability of the site.

The changes to markup of external links using "Markdown syntax" rather than "HTML syntax" (as compared in #57) makes it easier to change in future I think. It's easier to search-replace.

2023-04-03 16:21 UTC, aiman commented on static/favicons/favicon.ico
Favicon seems to have been initially added in 0bbd408, but don't think it was added in the right place as it has been broken until now. So please delete the legacy file and keep the new one added.

2023-04-03 16:22 UTC, aiman requested changes
Just the old favicon to delete.

2023-04-04 09:15 UTC, cmjc commented on static/favicons/favicon.ico
@aiman the favicon needs to be in 2 places for this reason:

- `./static/favicon.ico`: on site generation the favicon is copied to the root of the published site (more specifically, to the `config.toml` `baseURL` value set:`https://docs.autonity.org/`.  https://docs.autonity.org/favicon.ico will then resolve to show a page with the icon displayed in the centre. Without this, it will resolve to a not found error page. This was the reason for the PR adding it  #46 
- `.static/favicons/favicon.ico`: this is the edit made for the favicon to be shown in the browser tab (https://www.docsy.dev/docs/adding-content/iconsimages/#add-your-favicons).

2023-04-04 09:38 UTC, aiman commented on static/favicons/favicon.ico
Thanks for explaining. This approach is not ideal because it retains the Docsy favicon template that makes use of http://cthedot.de/icongen, but we aren't supplying all the other icon images it inserts into the HTML, and so they use a dummy icon.

One way forward:

- delete the `static/favicons/favicons.ico`
- create new file `layouts/partials/favicons.html` with the content below to override Docsy's built-in template:

```html
<!-- Override Docsy favicon layout -->
<link rel="shortcut icon" href="{{ "favicon.ico" | relURL }}" >
```

2023-04-04 09:43 UTC, aiman commented on static/favicons/favicon.ico
Alternatively one could retain use of Docsy's favicon generator <http://cthedot.de/icongen> by using that site to generate favicons for many sizes and platforms, and place them in `static/favicons/`.

2023-04-04 14:29 UTC, cmjc commented on static/favicons/favicon.ico
Correct! Edited for change request in commits 378427b4cb65fbae18a76312e33e9dd4164d94db , f27021f4609cf5b161e2214a6e083da45793f77c . 

Changes:

- Generated additional icons using icongen and added to favicons
- Removed file `/static/favicons/favicons.ico`
- Added layout `favicons.html` edited to add in `link` tags for the additional icongen icons generated:

```html
<!-- Override Docsy favicon layout -->
<link rel="shortcut icon" href="{{ "favicon.ico" | relURL }}" type="image/x-icon" />
<link rel="apple-touch-icon" href="/favicons/apple-touch-icon.png" type="image/png" />
<link rel="icon" sizes="192x192" href="/favicons/android-chrome-192x192.png" type="image/png" />
<link rel="icon" sizes="512x512" href="/favicons/android-chrome-512x512.png" type="image/png" />
<link rel="icon" sizes="192x192" href="/favicons/android-chrome-maskable-192x192.png" type="image/png" />
<link rel="icon" sizes="512x512" href="/favicons/android-chrome-maskable-512x512.png" type="image/png" />
```

(icongen originally gave the android-chrome icons `rel` values derived from the icon filename generated. E.g. `android-chrome-192x192`). That is incorrect according to ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#icon .)

2023-04-04 18:38 UTC, aiman commented on static/favicons/favicon.ico
I am confused - why use a custom template instead of just adding all the icons matching Docsy's built-in `layouts/partials/favicons.html` "as is"?

Reviewing the icons on Github, they don't look quite right - the logo isn't actually scaled to the dimensions, rather just surrounded by empty space. Did you use SVG file as 
input to the tool? It has to be SVG not PNG, as only SVG is scalable.

Please go for option 1 or option 2 for now.

2023-04-06 08:45 UTC, cmjc commented on static/favicons/favicon.ico
OK, reverted to option 1. Please see commit be1c302dc671ccf699e507283dc700e516c431f7

2023-04-06 15:02 UTC, aiman approved these changes
LGTM

2023-04-06 16:26 UTC, merged